### DISCUSSION TITLE
Is it possible to access work items and commits from a resources pipeline?

### DISCUSSION THREAD

**Discussion by gchorkawy** [rfennell/AzurePipelines#1016] [Q&A] [answered]
Hello,

Is it possible to access the work items and commits from pipelines that are included as resources?

For example, my main pipeline includes pipelineA and pipelineB as resources. I would like to include work items and commits details from the 3 pipelines in my release notes.

Here is an overview of my main pipeline:

```
trigger:
- master

resources:
  pipelines:
  - pipeline: pipelineA
    project: myProject
    source: sourceA
    branch: master
    trigger:
      branches:
        include:
        - master
  - pipeline: pipelineB
    project: myProject
    source: sourceB
    branch: master
    trigger:
      branches:
        include:
        - master

stages:
  - stage: publishDev
    displayName: publish to DEV
    jobs:
      - deployment: DeployDev
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: XplatGenerateReleaseNotes@3
                  displayName: Release Notes
                  inputs:
                    outputfile: '$(Build.ArtifactStagingDirectory)\ReleaseNotes-DEV.md'
                    templateLocation: 'File'
                    templatefile: '$(Build.SourcesDirectory)\template.md'
                    checkStage: true
                    dumpPayloadToConsole: true
                    dumpPayloadToFile: false
                    replaceFile: true
                    getParentsAndChildren: false
                    getAllParents: false
                    getIndirectPullRequests: false
                    stopOnError: true

  - stage: publishQA
    displayName: publish to QA
    dependsOn: ["publishDev"]
    #condition:  and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
      - deployment: DeployQA
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: XplatGenerateReleaseNotes@3
                  displayName: Release Notes
                  inputs:
                    outputfile: '$(Build.ArtifactStagingDirectory)\ReleaseNotes-QA.md'
                    templateLocation: 'File'
                    templatefile: '$(Build.SourcesDirectory)\template.md'
                    checkStage: true
                    dumpPayloadToConsole: true
                    dumpPayloadToFile: false
                    replaceFile: true
                    getParentsAndChildren: false
                    getAllParents: false
                    getIndirectPullRequests: false
                    stopOnError: true

  - stage: publishProd
    displayName: publish to Prod
    dependsOn: ["publishQA"]
    #condition:  and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
      - deployment: DeployProd
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: XplatGenerateReleaseNotes@3
                  displayName: Release Notes
                  inputs:
                    outputfile: '$(Build.ArtifactStagingDirectory)\ReleaseNotes-PROD.md'
                    templateLocation: 'File'
                    templatefile: '$(Build.SourcesDirectory)\template.md'
                    checkStage: true
                    dumpPayloadToConsole: true
                    dumpPayloadToFile: false
                    replaceFile: true
                    getParentsAndChildren: false
                    getAllParents: false
                    getIndirectPullRequests: false
                    stopOnError: true

```

Thanks,
Greg
