### DISCUSSION TITLE
WikiUpdaterTask: Prepend contents after TOC?

### DISCUSSION THREAD

**Discussion by gchorkawy** [rfennell/AzurePipelines#1038] [Q&A] [answered]
Hello,

Is it possible to prepend contents after the table of contents keyword (`[[_TOC_]]`)?

Here is an example of what I am trying to achieve:

![image](https://user-images.githubusercontent.com/46079630/125099441-03549580-e0a6-11eb-936a-a54636710ec1.png)

Here is the task in my pipeline yml:

```
  - task: WikiUpdaterTask@1
    inputs:
      repo: '$(GitUrl)'
      filename: 'test.md'
      replaceFile: false
      appendToFile: false
      dataIsFile: true
      sourceFile: 'ReleaseNotes.md'
      message: 'Update from pipeline'
      gitname: 'builduser'
      gitemail: 'build@demo'
      useAgentToken: true
      localpath: '$(System.DefaultWorkingDirectory)\repo'
```

Thanks for your help,
Greg

**Comment by rfennell** [comment, marked as answer]
No sorry, there is no way to archive what you are after using my task.

I feel trying to add this functionality to my WIKIUploader task is just a bit too much scope creep. So, all I can suggest is use a PowerShell/Bash task to remove the old `[[TOC]]` in the pipeline. Something like:

1. Generate Release Notes with a `[[TOC]]` at the top of the template.
2. Use a PowerShell/Bash script to update the current WIKI page removing the `[[TOC]]` - [See this on running Git commands in scripts](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml)
3. Prepend the new release notes.

**Reply by gchorkawy** [reply]
I’ll do that. Thanks for the tip!

**Reply by gchorkawy** [reply]
hi @rfennell,

I have tried the steps described above. For some reason the release notes contain REPLACEMENT CHARACTER [U+FFFD �](https://en.wikipedia.org/wiki/Specials_(Unicode_block)) throughout. 

Here is a summary of what I am observing for each step:

1. Release notes markdown is generated with ```[[_TOC_]]``` keyword at top of document.
2. To remove ```[[_TOC_]]``` keyword from current wiki page I use the following in my pipeline:

```
resources:
  repositories:
  - repository: MyWiki
    type: git
    name: MyWiki
    ref: main

...

steps:
  - checkout: MyWiki
    persistCredentials: true
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Set-Content -Path .\test.md -Value (Get-Content -Path .\test.md | Select-String -Pattern '[[_TOC_]]' -NotMatch)
        git config user.email "builduser@email.com"
        git config user.name "builduser"
        git commit -a -m "remove TOC keyword"
        git push origin HEAD:main
      workingDirectory: '$(Build.SourcesDirectory)\MyWiki'
```

I can see in the wiki revisions that the TOC keyword is removed, and wiki does not contain REPLACEMENT CHARACTER.

3. The release notes corresponding to the latest build are prepended correctly with the TOC. But the original release notes text is modified such that a REPLACEMENT CHARACTER is injected in between each character. See image below.

Note that this issue occurs with and without the TOC keyword.

![image](https://user-images.githubusercontent.com/46079630/125349007-f694a380-e32a-11eb-997f-1f09c4512144.png)


Finally, I was able to achieve my goal by using the following powershell task to prepend the release notes, and git commands to publish to wiki.

```
$(Get-Content -Path $(Build.ArtifactStagingDirectory)\ReleaseNotes.md; Get-Content -Path .\$test.md | Select-String -Pattern '[[_TOC_]]' -NotMatch) | Set-Content -Path .\test.md
git config user.email "builduser@email.com"
git config user.name "builduser"
git commit -a -m "Update from build pipeline"
git push origin HEAD:main
```

I would prefer, however, to use your task. Would it be possible to add an option to your task to do something similar to this powershell script?

Thanks,
Greg
