### DISCUSSION TITLE
date_formatter module not working

### DISCUSSION THREAD

**Discussion by alvinvinalon** [rfennell/AzurePipelines#1091] [Q&A]
We are using the latest version of this extension and the task fails on generating the file whenever we use date_formatter.

##[error]Error Processing handlebars [Error: Missing helper: "date_formatter"]

We have this version installed: 3.65.2 (Latest)

Is there anything we need to configure in Azure devops to load the date_formatter module?
Also, the [example usage](https://github.com/rfennell/AzurePipelines/blob/main/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203/date_formatter.js) looks like it's missing a mustache 
/* Usage
    {{date_formatter buildDetails.startTime}
*/

should it be {{date_formatter buildDetails.startTime}} ?

Anyway, even after using {{date_formatter buildDetails.startTime}}, the date_formatter doesn't work and the file doesn't get generated.

Cheers

**Comment by rfennell** [comment]
A detailed in the [WIKI](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task) you have to tell the task where custom extension is stored. This can be inline or a file

> Finally there is also support for your own custom extension libraries. These are provided via an Azure DevOps task parameters holding either a block of JavaScript or the path to filename containing the JavaScript which is loaded into the Handlebars templating engine.
> 
> Either as inline javaScript
> 
> Note: Inline JavaScript can be entered in the YAML as a single line or a multi-line parameter as follows using the | operator
>
``` 
- task: XplatGenerateReleaseNotes@3
   inputs:
      outputfile: '$(Build.ArtifactStagingDirectory)\releasenotes.md'
      # all the other parameters required
      customHandlebarsExtensionCode: |
         module.exports = {foo() {
            return 'Returns foo';
        }};
```

> Or the custom extension can be passed as file
> 

```
 - task: XplatGenerateReleaseNotes@3
    inputs:
      outputfile: '$(Build.ArtifactStagingDirectory)\releasenotes.md'
       # all the other parameters required
       customHandlebarsExtensionFile: $(System.SourceDirectory)\customcode.js
```

> Either way it can be consumed in a template as shown below
> 
```
 ## To confirm our custom extension works
 We can call our custom extension {{foo}} 

```

**Reply by jamers99** [reply]
I have a similar problem, but I specified the file and it's not working... Any ideas?

**YAML**
```
  - task: XplatGenerateReleaseNotes@3
    inputs:
      outputfile: '$(Pipeline.Workspace)\release-notes.html'
      templateLocation: 'File'
      templatefile: '$(Build.SourcesDirectory)\azure-pipelines\templates\deploy\release-notes\template.html'
      checkStage: true
      dumpPayloadToConsole: false
      dumpPayloadToFile: false
      replaceFile: true
      customHandlebarsExtensionFile: '$(Build.SourcesDirectory)\azure-pipelines\templates\deploy\release-notes\count_workitems_by_type.js'
      getParentsAndChildren: false
      getAllParents: false
      getIndirectPullRequests: false
      stopOnError: true
      considerPartiallySuccessfulReleases: true
      checkForManuallyLinkedWI: false
      wiqlWhereClause: '[Custom.Releasenotesapproved] = true AND [Custom.IncludeinReleaseNotes] Contains "{{ parameters.appName }}"'
```
**Template**
```
<h2>New features in build {{buildDetails.buildNumber}}</h2>
<ul>
    {{#forEach queryWorkItems}}
    <li><b>{{this.id}}</b>: {{lookup this.fields 'Custom.ReleaseNoteHeader'}}<br/>{{lookup this.fields 'Custom.ReleaseNoteBody'}}</li>
    {{/forEach}}
</ul> 

<h3>Squashed <b>{{count_workitems_by_type this.workItems "Bug"}}</b> bugs</h2>
```
**Extension**
```
// A Handlebars Helper to count the number of work items of a given type
/* Usage
- Total WI {{this.workItems.length}}
- Bugs {{count_workitems_by_type this.workItems "Bug"}} 
- Product Backlog Item {{count_workitems_by_type this.workItems "Product Backlog Item"}} 
*/

module.exports = {count_workitems_by_type(array, typeName) {
    return array.filter(wi => wi.fields['System.WorkItemType'] === typeName).length;}
};
```
