### DISCUSSION TITLE
XplatGenerateReleaseNotes error in yml pipeline - Cannot find module 'azure-pipelines-task-lib/task'

### DISCUSSION THREAD

**Discussion by Smiffc0** [rfennell/AzurePipelines#1121] [Q&A]
Hi Richard. I have developed some custom extensions using the test console and am now trying to run the same via a yml pipeline but I get the following error: `##[error]Error: Cannot find module 'azure-pipelines-task-lib/task'`. 

The extension file is in the form `module.exports = {...` 

Below is the config set on the task:

```
- task: XplatGenerateReleaseNotes@3
  inputs:
    outputfile: '<path_to>/ReleaseNotes.md'
    templateLocation: 'File'
    templatefile: '<path_to>/simple-template.md'
    customHandlebarsExtensionFile: 'customHandlebars.js'
    customHandlebarsExtensionFolder: '<path_to_customHandlebarsExtensionFolder>'
    # all the other parameters required
```

Am i missing something? Do I have to run a task prior to this to install the azure module?

Many thanks
