### DISCUSSION TITLE
Branch

### DISCUSSION THREAD

**Discussion by Sampanna** [rfennell/AzurePipelines#1366] [Q&A]
- How do i specify a target branch and to generate notes for builds related to PRs/Commits associated with it?
- Specifying to and from build ranges gets me items from the past which shouldnt be part of the release notes. Any thoughts on how to troubleshoot to get to the exact cause? How to fix it?
For e.g. A Bug item closed on 30/08 shouldn't have appeared on the notes generated from 3rd Oct - 18th Oct. This Item was closed as a part of Sprint 15 and shouldn't have appeared in Sprint 20/21's release notes for above date range

![image](https://user-images.githubusercontent.com/6469851/196658330-34fecdbf-df3a-44c5-b877-d8769a41c19f.png)
![image](https://user-images.githubusercontent.com/6469851/196658521-a68bb061-ee2e-4a06-8686-91e0bedd9354.png)

Build settings:
```
{
    "TeamFoundationCollectionUri": "https://dev.azure.com/x",
    "TeamProject": "GitHub",
    "buildId": "",
    "releaseDefinitionId": "",
    "releaseId": "",
    "environmentName": "Windows",
    "templatefile": "build-handlebars-template.md",
    "outputfile": "output.md",
    "dumpPayloadToConsole": "true",
    "dumpPayloadToFile": "true",
    "dumpPayloadFileName": "payload.json",
    "templateLocation": "File",
    "inlinetemplate": "",
    "outputVariableName": "no available in this tool",
    "showOnlyPrimary": "false",
    "replaceFile": "true",
    "appendToFile": "false",
    "getParentsAndChildren": "true",
    "getAllParents": "true",
    "searchCrossProjectForPRs": "true",
    "stopOnRedeploy": "false",
    "SortWi": "true",
    "SortCS": "true",
    "customHandlebarsExtensionCodeAsFile": "",
    "customHandlebarsExtensionCode": "",
    "customHandlebarsExtensionFile": "customHandlebars.js",
    "customHandlebarsExtensionFolder": ".\\testconsole",
    "overrideStageName": "",
    "checkStage": "true",
    "Fix349": "true",
    "tags": "",
    "overrideActiveBuildReleaseId": "",
    "overrideBuildReleaseId": "",
    "getIndirectPullRequests": "false",
    "considerPartiallySuccessfulReleases": "false",
    "checkForManuallyLinkedWI": "false",
    "wiqlWhereClause": "",
    "getPRDetails": "true",
    "getTestedBy": "true",
    "maxRetries": "3",
    "pauseTime": "5000",
    "stopOnError": "false"
}
```

DevOps Task:
```

- task: XplatGenerateReleaseNotes@3
            enabled: true
            inputs:
              outputfile: "$(Build.ArtifactStagingDirectory)/releasenotes.md"
              templateLocation: "File"
              templatefile: "Myriad - VPP/azure-pipeline/pipelines/build-handlebars-template.md"
              dumpPayloadToConsole: false
              dumpPayloadToFile: false
              replaceFile: True
              getParentsAndChildren: False
              getAllParents: False
              getIndirectPullRequests: False
              stopOnError: False
              considerPartiallySuccessfulReleases: False
              checkForManuallyLinkedWI: False
              # checkStage: true
              # tags: 'release*'
              wiqlWhereClause: "$(wiqlWhereClause)"
              wiqlFromTarget: "WorkItems"
              overrideBuildReleaseId: $(toBuildId)
              OverrideActiveBuildReleaseId: $(fromBuildId)

```
