### DISCUSSION TITLE
101 - AssemblyVersion.cs

### DISCUSSION THREAD

**Discussion by thyme51** [rfennell/AzurePipelines#1460] [Q&A]
I guess I miss something fundamental here :-) .

For test purposes, I'm publishing a simple .NetFx48 function as a NuGet package to my own Azure DevOps artifact feeds
`namespace CalculatorAdd
{
    public class Class1
    {
        public int Add(int a, int b) { return a + b; }
    }
}`

My yml looks like
```
variables:
  PackageVersion: $(Major).$(Minor).$(Patch)
  system.debug: true
  
steps:
- bash: env | sort
- script: echo $(PackageVersion)

- task: VersionAssemblies@3
  inputs:
    Path: '$(Build.SourcesDirectory)'
    VersionNumber: '$(PackageVersion).1'
    InjectVersion: true
    FilenamePattern: 'AssemblyInfo.*'
    OutputVersion: "OutputedVersion"
```
The task VersionAssemblies@3 runs smooth and produces output like
```
##[debug]D:\a\1\s\Sandkasse\CalculatorAdd\Properties\AssemblyInfo.cs - version applied
##[debug]Updating all version fields
##[debug]Set the output variable 'OutputedVersion' with the value 2.0.11.1
```
However, after packing the NuGet package following VersionAssemblies@3 (same yml job/steps)

```
- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: '**/CalculatorAdd.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: byEnvVar 
    versionEnvVar: PackageVersion
```
my "Calculator" still has Version 1.0.0.0 when installed in a simple console application:
![image](https://user-images.githubusercontent.com/8446402/212325435-7805d5ca-ab83-4295-844b-b1677d44cb9c.png)

I expect my NuPkg to have version 2.0.11 and C# Assembly 2.0.11.1 in this test.
Thanks

**Comment by rfennell** [comment]
Yes, I would expect the same too.

Can you upload a copy of the sample (zip of the source and all the YAML and other config files) and I will experiment with it and find out the issues

**Comment by thyme51** [comment]
Excellent

This is the complete raw log 
[Pipeline raw log.txt](https://github.com/rfennell/AzurePipelines/files/10418665/Pipeline.raw.log.txt)

This is a simple c# class library. 
[CalculatorAdd.zip](https://github.com/rfennell/AzurePipelines/files/10418657/CalculatorAdd.zip)

This is my yml file 
[VersionPackPublishToNuget.zip](https://github.com/rfennell/AzurePipelines/files/10418660/VersionPackPublishToNuget.zip)

Thanks,

**Reply by rfennell** [reply]
I see from your YML you don't build the project after you have set the version in the `assemblyinfo.cs` file. 

You have to do this as my tasks needs to set the version value **prior** compilation, as you have to do for any .NET assemblies (editing the .cs file, not the DLL). This is unlike interpreted languages where you can set the value after or during packaging.

So your steps need to be something like

```yaml
steps:
- bash: env | sort

- script: echo $(PackageVersion)

# As for demo purposes, I wanted to show you could have different version schemes for Nuget and .Net Assemblies
# Nuget 3.0.0
# Assembly: 3.0.0.123

- task:  Version-Assemblies-Task.VersionAssemblies@3
  inputs:
    Path: '$(Build.SourcesDirectory)'
    VersionNumber: '$(PackageVersion).123'
    InjectVersion: true
    FilenamePattern: 'AssemblyInfo.*'
    OutputVersion: "OutputedVersion"
  
- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: '**/CalculatorAdd.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: byEnvVar 
    versionEnvVar: PackageVersion
```
