### DISCUSSION TITLE
Gitflow-template.hbs

### DISCUSSION THREAD

**Discussion by H-mmer** [rfennell/AzurePipelines#1515] [Q&A]
Could someone provide me an example task for gitflow-template.hbs.
I'm kinda confused about it since it has those conditions `{{#if (eq (template) 'production')}}`

Do i need multiple templates or just the one provided? Also read some other issue that you're supposed to change the extension function to something else.

This is my current full pipeline:

```
trigger:
  - main
  - develop
  - release

pool:
  vmImage: ubuntu-latest

## Job to create release and add tag
jobs:
  - job: CalculateVersion
    displayName: Tagging release version

    steps:
      # Checkout with persist credentials
      - checkout: self
        persistCredentials: true
        fetchDepth: 0

      # Install GitVersion
      - task: gitversion/setup@0
        displayName: Install GitVersion
        inputs:
          versionSpec: "5.x"

      # Determine the semantic version
      - task: gitversion/execute@0
        displayName: Calculating version
        inputs:
          useConfigFile: True
          configFilePath: ".azuredevops/gitversion.yml"

      # Update Build.BuildNumber to use SemVer, as by default it uses FullSemVer
      - pwsh: |
          Write-Host "##vso[build.updatebuildnumber]$(GitVersion.SemVer)"
        displayName: Update Build.BuildNumber


      # Adds the tag for the calculated semantic version
      - task: PowerShell@2
        displayName: Adding git release tag
        inputs:
          targetType: inline
          script: |
            Write-Host "Configuring git author info.." -ForegroundColor Cyan
            git config --local user.name "Azure DevOps pipeline"
            git config --local user.email "Azure.Devops.pipeline@example.com"
            Write-Host "Adding git tag for release $(GitVersion.SemVer).." -ForegroundColor Cyan
            git tag -a $("v$(GitVersion.SemVer)") -m $("Release $(GitVersion.SemVer)")
            Write-Host "Doing git push.." -ForegroundColor Cyan
            git push --tags
            Write-Host "Done." -ForegroundColor Cyan

  ## Job to create release notes file and publish it to the wiki
  - job: CreateReleaseNotes
    displayName: Creating release notes
    dependsOn: CalculateVersion
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

    steps:
      # Generates a release notes file
      - task: XplatGenerateReleaseNotes@4
        displayName: "Generate release notes"
        inputs:
          outputfile: '$(System.DefaultWorkingDirectory)\releasenotes.md'
          templateLocation: File
          templatefile: ".azuredevops/release-notes-template.md"
          dumpPayloadToConsole: true
          dumpPayloadToFile: true
          replaceFile: true
          getParentsAndChildren: False
          getAllParents: False
          getIndirectPullRequests: False
          stopOnError: True
          considerPartiallySuccessfulReleases: False
          checkStage: true
```
