### DISCUSSION TITLE
How end with new line with inlinetemplate?

### DISCUSSION THREAD

**Discussion by vernou** [rfennell/AzurePipelines#1522] [Q&A]
I want a file that contains all release notes.
The generated release notes is append at the begin at this file.
I pass the template by the parameter `inlinetemplate` :

```yaml
- task: XplatGenerateReleaseNotes@4
  displayName: 'Append release notes'
  inputs:
    checkStage: true
    getParentsAndChildren: false
    replaceFile: false
    appendToFile: false
    outputfile: '$(Build.SourcesDirectory)\doc\release-notes.md'
    templateLocation: 'InLine'
    inlinetemplate: |+
      **{{buildDetails.definition.name}}** {{buildDetails.buildNumber}} ({{moment buildDetails.startTime 'DD/MM/YYYY' }})
      
      {{#forEach workItems}}
      - [{{lookup this.fields 'System.WorkItemType'}} - {{lookup this.fields 'System.Title'}}]($(WorkItemBaseUrl)/{{this.id}})
      {{/forEach}}
      
      ---
       

- task: ...
```

 But it seem the final end line is ignored :

```txt
**npm-my-awesone-librairie** 4.0.23062711 (27/06/2023)


---**npm-my-awesone-librairie** 4.0.23062710 (26/06/2023)


---**npm-my-awesone-librairie** 4.0.23062709 (25/06/2023)


---
```

Do you now how append a break line to the end of the generated release notes before to push the release notes at the begin at a file?

---

EDIT : I tested with the template in a file and the final end line is correctly present in the generated release notes.
