### DISCUSSION TITLE
No build detected with checkStage to true

### DISCUSSION THREAD

**Discussion by misecca** [rfennell/AzurePipelines#1559] [Q&A]
I want to to generate a changelog between a tag and the current build. 

Follow the wiki I set:
- checkStage: true
- tags: 0.3.6 (just an example)

My azure pipeline is triggered manually with two stages:
- first stage build the application
- second stage calculate the change log

I use the version 3 of  XplatGenerateReleaseNotes

This is the task

   ``` yaml
- task: XplatGenerateReleaseNotes@3
      inputs: 
        tags: '0.3.6'
        checkStage: true
        templatefile: 'xxx/change-log-template.md'
        outputfile: 'xxx/changelog.md'
        outputVariableName: 'outputvar'
        templateLocation: 'File'  
        dumpPayloadToFile: True
        dumpPayloadFileName: xxx/payload.json
        dumpPayloadToConsole: false        
        replaceFile: True
        appendToFile: True
        getParentsAndChildren: True
        getAllParents: True
        getIndirectPullRequests: False
        stopOnError: False
        considerPartiallySuccessfulReleases: False
        checkForManuallyLinkedWI: False  
```

From log I see:

Getting the current build details
Only considering builds with the tag(s) '0.3.6'
Getting items associated the builds since the last successful build to the stage 'ChangeLog'
Found '3' matching builds to consider
Matching 'successful' builds only 
Comparing 1346710 against 1346710
Ignore compare against self
Comparing 1346680 against 1346710
Skipping build as does not have the correct tags
Comparing 1346675 against 1346710
Skipping build as does not have the correct tags
**There has been no past successful build for this stage, we need to get the details for all past builds**
Using workaround for build API limitation (see issue #349)

The result is that I made a comparison among all the previous build and the current one.

I use the same XplatGenerateReleaseNotes@3 with checkStage set to false and it work correctly (in this case the pipeline is triggered automatically when I push on main)
