### DISCUSSION TITLE
Specifying a separate Repository for GenerateReleaseNotes Extension in Azure DevOps Pipeline

### DISCUSSION THREAD

**Discussion by ArneReith** [rfennell/AzurePipelines#1590] [Q&A]
I have a Repository where I store all my Azure Devops YAML Pipelines and other related materials like templates an bash scripts. The pipelines are executed within this repository. The actual project, wich contains the application itself, is loaded from a separate repository via resources:

```
resources:
  repositories:
  - repository: "projectrepo"
    type: git
    name: myapplication
```

I've integrated the GenerateReleaseNotes Extension in a pipeline task. Currently it generates the release notes for the main project, which includes the pipelines. However, I would like the release notes to be generated for the projectrepo instead.

Is it possible to specify the repository that should be used for generating the release notes?

Thank you,
Arne
