### DISCUSSION TITLE
Pull commits from another repo other than the primary repository associated with the pipeline ?

### DISCUSSION THREAD

**Discussion by jaysidri** [rfennell/AzurePipelines#1877] [Q&A]
Is there a way to specify a repo other than the one associated with the pipeline? 

My build pipe pulls down my source code as a step:

```
  - script: 'git clone --branch $(releaseBranch) --depth 1 https://anything:$PAT@company.visualstudio.com/projectx/_git/project1 $(System.DefaultWorkingDirectory)/project1'
    displayName: 'Check out source from branch'
    env:
      PAT: $(PAT)  

```

and generates the release notes at the end of the build:

```
  - task: richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes.XplatGenerate-Release-Notes.XplatGenerateReleaseNotes@2
    displayName: 'Generate Release Notes based on Release Comparision API'
    inputs:
      outputfile: '$(System.DefaultWorkingDirectory)/ReleaseNotes.md'
      outputVariableName: ReleaseNotesOutput
      templateLocation: InLine
      inlinetemplate: '{{#each commits}}{{truncateOnNewLine this.message}}{{/each}}'
      customHandlebarsExtensionCode: |
        module.exports = {
            truncateOnNewLine:function(str) {
                if (str.indexOf("Merged PR") === 0) {
                    var newlineIndex = str.search(/\r\n|\r|\n/g);
                    if (newlineIndex > -1) {
                        return "* " + str.slice(16, newlineIndex) + "\n";
                    }
                    return "* " + str.slice(16, 100) + "\n";
                }
            }
        };
```

It's not going to find "Merged PR" commits since the repo the build script lives doesn't contain source code (just configuration files required to complete the build).
