### DISCUSSION TITLE
Generating wiki with hierarchy nodes

### DISCUSSION THREAD

**Discussion by arulconsultant** [rfennell/AzurePipelines#1955] [Q&A]
Any discussion links or guide to publish wiki inside hierarchial (Sub wiki like) 

![image](https://github.com/user-attachments/assets/02c96421-18da-4766-aee3-7b28c6c95d90)

**Comment by rfennell** [comment]
Have a look at one of my company's demo samples [Living the Dream](https://dev.azure.com/blackmarblelabs/Living%20The%20Dream). The WIKI on this system does what I think you want, as shown below

![image](https://github.com/user-attachments/assets/8f259038-7c8a-40d0-93ff-01df36ce8fed)

The work is done to generate the release notes and publish them using a [YAML template](https://dev.azure.com/blackmarblelabs/Living%20The%20Dream/_git/LivingTheDream?path=/YAMLTemplates/WIKIReleaseNotes.yml)

```yaml
parameters:
- name: template
  type: string 
- name: version
  type: string 

steps:
- task: XplatGenerateReleaseNotes@3
  displayName: 'Generate build release notes'
  inputs:
    outputfile: '$(System.DefaultWorkingDirectory)/ReleaseNotes.md'
    templateLocation: 'File'
    templatefile: '${{parameters.template}}'
    dumpPayloadToConsole: false
    dumpPayloadToFile: false
    replaceFile: True
    getParentsAndChildren: False
    getAllParents: False
    getIndirectPullRequests: False
    checkStage: true
    
- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks.WikiUpdaterTask.WikiUpdaterTask@1
  displayName: 'Git based WIKI Updater'
  inputs:
    repo: 'https://blackmarblelabs@dev.azure.com/blackmarblelabs/Living%20The%20Dream/_git/Living-The-Dream.wiki'
    filename: '$(System.StageName)/${{parameters.version}}.md'
    dataIsFile: true
    sourceFile: '$(System.DefaultWorkingDirectory)/ReleaseNotes.md'
    message: 'Release documentation creation'
    gitname: FabrikamRelease
    gitemail: 'FabrikamRelease@blackmarble.com'
    useAgentToken: true
```

This is a fully worked sample so should show you want you need
