### DISCUSSION TITLE
How to upload release notes to a folder

### DISCUSSION THREAD

**Discussion by Shafeeqts89** [rfennell/AzurePipelines#931] [Q&A] [answered]
Hi,
 I am using the Create release note task and single page wiki updater. All is working fine, we are using  "Append to the end of file" in the WIKI in the task. But now the file is growing very large and not easy to find due to the huge length. Is there any option to create a folder in the Azure DevOps WIKI and upload each release note to that folder instead of appending it to last?

**Comment by rfennell** [comment]
Yes there is, if the WIKI target filename includes a path that path should be created. So you can use `/folder/myfile.md`.

What I consider an even better solution is to use build variables in the parameter e.g. you could create a folder per release `$(build.buildnumber)/releasenotes.md`

Hope that helps

**Reply by Shafeeqts89** [reply]
thanks for the quick response, I shall try and get back to you.

**Reply by Shafeeqts89** [reply]
It worked, Thank you.
is there any predefined variable to write build Date, I could not see any in the official documentation?

**Comment by rfennell** [comment, marked as answer]
There is nothing out the box,  but there are workaround [see this post](https://stackoverflow.com/questions/44738944/vsotfs-get-current-date-time-as-variable)

Basically you need to have an inline script early in your pipeline that dynamically sets a pipeline variable (an environment variable in reality). You can then access this variable in later tasks 

Here is a basic example

```
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  name: rundate

steps:

- powershell: |
    $date=$(Get-Date -Format g);
    Write-Host "##vso[task.setvariable variable=rundate]$date"
  displayName: 'Set the date'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(rundate).zip'
    replaceExistingArchive: true
```

You can see it tries to generate a zip file name using the $(rundate) variable. Obviously you need to fiddle around with the date format so it is not invalid for your needs, but that all done in the script that generates the variable string

```
Starting: ArchiveFiles
==============================================================================
Task         : Archive files
Description  : Compress files into .7z, .tar.gz, or .zip
Version      : 2.179.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/archive-files
==============================================================================
Found 1 files
Archiving file: b
files=b
/usr/bin/zip -r /home/vsts/work/1/a/01/14/2021 10:02.zip b
  adding: b/ (stored 0%)
Finishing: ArchiveFiles
```
