### DISCUSSION TITLE
Single file from Wiki PDF export

### DISCUSSION THREAD

**Discussion by WebGoose** [rfennell/AzurePipelines#942] [Q&A] [answered]
I'm really struggling with the path for exporting a single page from the Wiki to PDF in my release. 

In the steps before I use your other tasks to generate release notes and commit to the Wiki in Devops which works perfectly. I'm trying now to export that release note entry to PDF so that I can email it out. 

Where am I going wrong with the path to the individual file? I feel like I've tried every possible permutation and I'm starting to lose my mind :) I'm probably just misunderstanding the instructions. 

This is how the wiki looks
![image](https://user-images.githubusercontent.com/5024960/107153367-cd37ac00-6975-11eb-9500-dd252f86f6af.png)

This is what the root folder looks like when you clone the wiki. The folder structure to the file goes /Releases/QA/file.md
![image](https://user-images.githubusercontent.com/5024960/107153424-3b7c6e80-6976-11eb-9c55-4c822e0843be.png)

This is how I have the task set up
![Task](https://user-images.githubusercontent.com/5024960/107153377-dcb6f500-6975-11eb-8970-09ed16cdf0d1.png)

And this is the error I'm getting. 
![Logs](https://user-images.githubusercontent.com/5024960/107153381-e93b4d80-6975-11eb-9621-5828aafdcd3b.png)

The wiki update task is working and adding the item and when I clone the repo the file is there so I'm not sure where I'm going wrong with the path to it. 

Any help would be greatly appreciated. 

Thank you!

**Comment by rfennell** [comment, marked as answer]
I think the confusion is that there are two ways the task can work, probably down to my documentation not being clear enough.

I had always assumed then when in single file mode a WIKI repo would not be cloned. The task would just be using the output from another task. This is my test case for that scenario

```
    - task: richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes-DEV1.XplatGenerate-Release-Notes.XplatGenerateReleaseNotes@2
      displayName: 'Generate Release Notes based on Release Comparision API'
      inputs:
        outputfile: '$(System.DefaultWorkingDirectory)\inline.md'
        outputVariableName: OutputText
        templateLocation: InLine
        inlinetemplate: |
          # Release notes 
          **Build Number**  : ${buildDetails.buildNumber} 
          **Build started** : ${buildDetails.startTime}  
          **Source Branch** : ${buildDetails.sourceBranch}  
          
          ### Associated work items  
          @@WILOOP@@  
          * ** ${widetail.fields['System.WorkItemType']} ${widetail.id} ** Assigned by: ${widetail.fields['System.AssignedTo']}  ${widetail.fields['System.Title']}  
          @@WILOOP@@  
            
          ### Associated commits
          @@CSLOOP@@  
          * **ID ${csdetail.commitId} ** ${csdetail.comment}    
          @@CSLOOP@@
    - task: richardfennellBM.BM-VSTS-WikiPDFExport-Tasks-DEV.WikiPDFExportTask.WikiPdfExportTask@1
      displayName: 'Export Single File'
      inputs:
        cloneRepo: false
        localpath: '$(System.DefaultWorkingDirectory)'
        singleFile: 'inline.md'
        outputFile: '$(Build.ArtifactStagingDirectory)\PDF\singleFile.pdf'
```

That said, there is no reason you should not do a clone if you wish and name a single file, you just make sure the clone path and the file path match up.  

Also you can export all or part of a WIKI repo as you wish, as these fragments show

```
    - task: richardfennellBM.BM-VSTS-WikiPDFExport-Tasks-DEV.WikiPDFExportTask.WikiPdfExportTask@1
      displayName: 'Export Azure DevOps WIKI'
      condition: succeededOrFailed()
      inputs:
        cloneRepo: true
        repo: 'https://dev.azure.com/richardfennell/GitHub/_git/GitHub.wiki'
        useAgentToken: true
        outputFile: '$(Build.ArtifactStagingDirectory)\PDF\Azrepo.pdf'
    - task: richardfennellBM.BM-VSTS-WikiPDFExport-Tasks-DEV.WikiPDFExportTask.WikiPdfExportTask@1
      displayName: 'Export part of the Azure DevOps WIKI'
      condition: succeededOrFailed()
      inputs:
        cloneRepo: true
        repo: 'https://dev.azure.com/richardfennell/GitHub/_git/GitHub.wiki'
        useAgentToken: true
        outputFile: '$(Build.ArtifactStagingDirectory)\PDF\AzrepoFilter.pdf'
        localpath: '$(System.DefaultWorkingDirectory)\repopartial'
        rootExportPath: '$(System.DefaultWorkingDirectory)\repopartial\folder'
```

A good tip if you are having problems is to run the pipeline on a private agent that you can RDP onto so you can see the file path, or drop a CMD/PowerShell/BASH script block in the pipeline that does  a directory listing the log
