### DISCUSSION TITLE
How to use single file wiki updater to publish release notes into sub-folder

### DISCUSSION THREAD

**Discussion by dion-snow** [rfennell/AzurePipelines#950] [Q&A] [answered]
Hi, I have the Wiki Updater task successfully publishing release notes to an Azure DevOps Wiki, but I cannot get it to publish the notes to a sub-folder e.g. Home/ReleaseNotes. I have specified the local path to be $(System.DefaultWorkingDirectory)\repo\Home\ReleaseNotes.md but this still publishes the notes to the parent folder.

Any idea on how to use the single file wiki updater task to publish the release notes into a subfolder? Thanks!

**Comment by rfennell** [comment, marked as answer]
The local path is just where the temporary clone of the wiki repo is stored.

This is a sample block of YAML for adding a folder to contain a file, the key is the `filename`. If it includes a path that will be created if it is already not present

```
- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks-DEV.WikiUpdaterTask.WikiUpdaterTask@1
   displayName: 'Git based WIKI Updater - GitHub folder'
   inputs:
        repo: github.com/rfennell/demorepo.wiki
        filename: TestFolder/PageFromWikiUpdater.md
        contents: |
            Header
             ---
            Some text
             ---
             Footer
       message: 'Update from Release - $(Release.ReleaseName)'
       gitname: builduser
       gitemail: 'build@demo'
       user: rfennell
       password: '$(githubPAT)'
       localpath: '$(System.DefaultWorkingDirectory)\githubrepo'
```
