### DISCUSSION TITLE
Cannot read property 'replace' of undefined

### DISCUSSION THREAD

**Discussion by lucasssfigueredo** [rfennell/AzurePipelines#967] [Q&A] [answered]
Hi.

I´m trying to use the WIKI Updater Task after the Generate Release Notes Task, and I am receiving the following error:

TypeError: Cannot read property 'replace' of undefined

[Generate Release Notes Task.log](https://github.com/rfennell/AzurePipelines/files/6109387/Generate.Release.Notes.Task.log)
[WIKI Updater Task.log](https://github.com/rfennell/AzurePipelines/files/6109389/WIKI.Updater.Task.log)

I am using a private host.

**Comment by rfennell** [comment, marked as answer]
The issue is you have not passed in the source name of the file generated by the previous task, or set the `isdata` parameter. I know the parameters can be confusing as their are input and output file name

You need something like this, I have only show the 3 key parameters 

```
        - task: WikiUpdaterTask@1
          displayName: 'Update Project Wiki with release notes'
          inputs:
           ...       
            filename: 'Builds/ReleaseNotes_25.md'   < this is the folder and/or the filename in the target WIKI
            sourceFile: 'ReleaseNotes_25.md'        < this is the path to the file generated by the other task
            dataIsFile: True                        < this is important, else it look for a string to be passed in not a file   
           ......
```

The `sourcefile` and `filename` can have different names.

See the [WIKI](https://github.com/rfennell/AzurePipelines/wiki/WIKI-Updater-Tasks-YAML) for the full documentation
