### ISSUE TITLE
[GenerateReleaseNotesXPlat] Workitems from Github repo not being reported

### ISSUE THREAD

**Issue by tr-fteixeira** [rfennell/AzurePipelines#1066]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Describe the bug

Using a Github.com repo as source, even though items are linked to the build, and it is discovered by some of the code (seen on debug logs), it is not added to the list and can't be used. 

Task configuration: 
``` yaml
        - task: richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes.XplatGenerate-Release-Notes.XplatGenerateReleaseNotes@3
          displayName: 'Generate Release Notes'
          inputs:
            outputfile: '$(System.DefaultWorkingDirectory)/inline.md'
            outputVariableName: OutputText
            templateLocation: InLine
            inlinetemplate: |
              {{#forEach workItems}}
              {{this.id}}|{{lookup this.fields 'System.IterationPath'}}|{{lookup this.fields 'System.AreaPath'}}
              {{/forEach}}
```

### Repo Steps

```bash
1. Use this task with a Github.com source repo.
2. Try to list WorkItems only linked via #123 pattern.
3. See items identified on debug logs
4. See no items identified on global WI list
```

### Expected Behavior

```bash
WorkItems should be added to the list and be available on output.
```

### Logging Information

```bash
Expanded truncated commit messages 0
Find any WorkItems linked from GitHub using the AB#123 format
##[debug]The commit 8bd11f2 is from a GitHub hosted repo
##[debug]Found 1 workitems linked using the AB#123 format, attempting to find details
##[debug]Adding details of workitem 233865
Adding 0 found using AB#123 links in GitHub comments
Removing duplicate WorkItems from master list
```
```
