### ISSUE TITLE
Error: Cannot find module 'handlebars'

### ISSUE THREAD

**Issue by Panda-Sharp** [rfennell/AzurePipelines#1136]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Describe the bug

I'm not sure if it's a bug or I'm missing something, but if I try to use this extension `https://raw.githubusercontent.com/rfennell/AzurePipelines/main/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203/each_with_sort_by_field.js` in a file I get the following error `Error: Cannot find module 'handlebars'`, but if I use it as `customHandlebarsExtensionCode` works fine.

### Repo Steps

Add this task

```
   - task: XplatGenerateReleaseNotes@3
      continueOnError: false
      inputs:
        outputfile: '$(System.DefaultWorkingDirectory)\$(Build.BuildNumber).md'
        templateLocation: 'File'
        templatefile: 'template.hbs'
        checkStage: true
        dumpPayloadToConsole: true
        dumpPayloadToFile: false
        replaceFile: true
       customHandlebarsExtensionFile: 'foo'
       customHandlebarsExtensionFolder: '$(System.DefaultWorkingDirectory)'
        getParentsAndChildren: false
        getAllParents: false
        getIndirectPullRequests: false
        stopOnError: true
        considerPartiallySuccessfulReleases: false
        checkForManuallyLinkedWI: false
```

add the following files in the root of the repo

foo.js
```
const handlebars = require("handlebars");
module.exports = {each_with_sort_by_field(array, key, opts) {
    if(opts.data) {
        data  = handlebars.createFrame(opts.data) 
    }

    // the sort
    array = array.sort (function (a, b) {
        a = a.fields[key]
        b = b.fields[key]
        if (a > b) return 1 
        if (a == b) return 0
        if (a < b) return -1
    });

    // the iterator
    var len = array.length;
    var buffer = '';
    var i = -1;
  
    while (++i < len) {
      var item = array[i];
      data.index = i;
      item.index = i + 1;
      item.total = len;
      item.isFirst = i === 0;
      item.isLast = i === (len - 1);
      buffer += opts.fn(item, {data: data});
    }
    return buffer;
}}
```
template.hbs

```
# Global list of WI ({{workItems.length}})
{{#each_with_sort_by_field   workItems "System.Tags"}}
{{#if isFirst}}## Associated Work Items (only shown if  WI) {{/if}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
   - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
   - **Tags** {{lookup this.fields 'System.Tags'}}
   - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
{{/each_with_sort_by_field  }}
```

run the pipeline

**Comment by rfennell** [comment]
I will have to check that and get back to you, should have time to look tonight

**Comment by rfennell** [comment]
This is a known issue see #832 and only appear when the task is run within a build pipeline (as opposed to the [test harness](https://github.com/rfennell/AzurePipelines/tree/main/Extensions/XplatGenerateReleaseNotes/V3/testconsole), why I had missed it earlier today when you raised it). 

The core of the issue is that the folder the custom script is generated into and loaded from needs to be the same as the one used by the other .JS files used by, and shipped with, the task.

Your options are
1. Use an inline custom script as you are doing - would be my choice as it does all the work for you
1. Use the alternate sort mechanism as detailed in #832 that does not need handlbars
1. Or you somehow need to get the custom script into the folder `...\_work\_tasks\XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb\3.74.3`. I could make this an option for the task, but it is something I have chosen to avoid doing as it seem wrong for a pipeline to update a task folder other than via the option used for option 1.

**Comment by Panda-Sharp** [comment]
Thanks I tried to search for, but I missed that issue, I'll take a look tomorrow 🙂

**Comment by rfennell** [comment]
I have another solution, and I think it is the one a favour if you don't want inline extension. 

All you need to do is `npm install` any modules into the same folder the `custom.js` is in e.g.

```
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(System.DefaultWorkingDirectory)'
    customCommand: 'install handlebars'

- task: XplatGenerateReleaseNotes@3
  inputs:
    outputfile: '$(Build.ArtifactStagingDirectory)/releasenotes.md'
    templateLocation: 'File'
    templatefile: '$(System.DefaultWorkingDirectory)/template.hbs'
    customHandlebarsExtensionFile: 'custom.js'
    customHandlebarsExtensionFolder: '$(System.DefaultWorkingDirectory)'
````

Using this model you can install any modules you need, so much more flexible.
