### ISSUE TITLE
New version 4.0.0 causes breaking change issue in extension

### ISSUE THREAD

**Issue by Pwd9000-ML** [rfennell/AzurePipelines#1149]
### Azure DevOps Extensions

WIKI PDF Generator

### Platform

Azure DevOps Services

### Extension Version

1.6.11

### Describe the bug

The below release of the tool produces an error, in the devops marketplace extension (aka wrapper):
(https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/releases/tag/4.0.0)

![image](https://user-images.githubusercontent.com/44137582/142383720-e00156ea-51bf-4e83-8622-ecfc48e49ba5.png)

Is it possible to resolve the header issue in the marketplace extension?
Or allow the version of the tool to be specified as a parameter in the extension?

If either of the above is possible that would be great.
Thanks!

### Repo Steps

Here is a copy of my YAML pipeline I am using, V3.3.0 works.
V4 gives the error : 
![image](https://user-images.githubusercontent.com/44137582/142383720-e00156ea-51bf-4e83-8622-ecfc48e49ba5.png)

In the YAML step that uses the tool, it would be great to be able to specify the version of the tool that should be downloaded as a param :)

```yaml
name: Wiki-To-PDF-$(Rev:rr)
trigger: none

stages:
- stage: wiki_export
  displayName: Wiki Export

  jobs:
  - job: wiki_to_pdf
    displayName: Wiki To PDF
    pool: xxxxx

    steps:
    - task: richardfennellBM.BM-VSTS-WikiPDFExport-Tasks.WikiPDFExportTask.WikiPdfExportTask@1
      displayName: 'Export a private Azure DevOps WIKI'
      inputs:
        cloneRepo: true
        branch: 'main'
        repo: 'xxxxxx.wiki'
        useAgentToken: true
        localpath: '$(System.DefaultWorkingDirectory)' 
        outputFile: '$(Build.ArtifactStagingDirectory)/PDF/Wiki.pdf'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish wiki export to Azure Pipeline'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/PDF'
        artifactName: DevOpsWiki
```

### Expected Behavior

Expect the pipeline to not fail and produce a PDF export

### Logging Information

Starting download of command line tool to C:\agent\_work\_temp
Downloading MaxMelcher/AzureDevOps.WikiPDFExport@4.0.0...
Download done
Using the EXE path of 'C:\agent\_work\_temp\azuredevops-export-wiki.exe' for AzureDevOps.WikiPDFExport
Cloning Repo
Using OAUTH Agent Token, overriding username and password
The provided repo URL is xxxxx.wiki
The protocol is https
The provided repo URL is xxxxx.wiki
Removing leading http:// or https:// block
Trimmed the URL to xxxxxx.wiki
URL used https://buildagent:***@dev.azure.comxxxxxx.wiki
Cleaned C:\agent\_work\955\s/CPWiki
Cloned xxxxxx.wiki to C:\agent\_work\955\s/CPWiki
Processing the contents of the folder 'C:\agent\_work\955\s/CPWiki' 
Adding the verbose flag to increase logging
Creating folder C:\agent\_work\955\a/PDF
Changing folder to C:\agent\_work\955\s/CPWiki
Using command '"C:\agent\_work\_temp\azuredevops-export-wiki.exe"  -p "C:\agent\_work\955\s/CPWiki" -o "C:\agent\_work\955\a/PDF/CPWiki.pdf" -v'

Failure processing application bundle.
Bundle header version compatibility check failed.
A fatal error occured while processing application bundle

##[error]Error: Command failed: "C:\agent\_work\_temp\azuredevops-export-wiki.exe"  -p "C:\agent\_work\955\s/CPWiki" -o "C:\agent\_work\955\a/PDF/CPWiki.pdf" -v
Failure processing application bundle.
Bundle header version compatibility check failed.
A fatal error occured while processing application bundle

##[error]Error: Command failed: "C:\agent\_work\_temp\azuredevops-export-wiki.exe"  -p "C:\agent\_work\955\s/CPWiki" -o "C:\agent\_work\955\a/PDF/CPWiki.pdf" -v
Failure processing application bundle.
Bundle header version compatibility check failed.
A fatal error occured while processing application bundle

Finishing: Export a private Azure DevOps WIKI

**Comment by rfennell** [comment]
I am on holiday this week, but there is a new release of my task scheduled to release with full cross platform support now V4 of the underlyingtask supports it. Should be out next week.

Until then stick with the 3x version of the PDF tool

**Comment by Pwd9000-ML** [comment]
Thank you so much for the update @rfennell 
Have a great time off! :)

**Comment by rfennell** [comment]
@Pwd9000-ML  I have had a look at adding the feature to download a specific version of the tools and decided not to add the feature at this time. 

The problem is the library I use to get the release asset, the EXE, just gets the latest version (as do all the others libraries I can find). I think it would be a waste of time to start writing new download client, or swap to raw REST calls, given I have to do a major update as the command-line options for the underlying tool have changed. That is a higher priority 

If you wish to use a specific version of the underlying tools I suggest you use the existing `overrideExePath` parameter to point to a previously downloaded version of the tools (FYI the reason I don't ship the tool within the extension is that it makes the VSIX too large to publish to the marketplace)

**Comment by rfennell** [comment]
I have just released V2 of this task that supports Windows and Linux (as this is what is supported by 4.0.0 of the underlying tool)

The AzureDevOps.WikiPDFExport tool since 4.0.0 is .NET 6 based. Hence [.NET 6](https://dotnet.microsoft.com/download/dotnet/6.0) must be installed on the agent.

In many cases this runtime will be present on a build agent e.g if VS2022 is installed. If it is not present it can be installed as a step in a build pipeline using the [usedotnet task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops) before this task is called.

> Note: this technique will work for both V1 and V2 of this task

```
steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core runtime'
  inputs:
    packageType: 'runtime'
    version: '6.0.x'
    includePreviewVersions: false
- task: richardfennellBM.BM-VSTS-WikiPDFExport-Tasks.WikiPDFExportTask.WikiPdfExportTask@2
  displayName: 'Export Single File'
  inputs:
    cloneRepo: false
    usePreRelease: false
    localpath: '$(System.DefaultWorkingDirectory)'
    singleFile: 'infile.md'
    outputFile: '$(Build.ArtifactStagingDirectory)/singleFile.pdf'
    ...
```
