### ISSUE TITLE
Support for updating `.order` files in subfolders

### ISSUE THREAD

**Issue by johanndev** [rfennell/AzurePipelines#1302]
### Azure DevOps Extensions

WIKI Updater

### Is your feature request related to a problem? Please describe.

As we are generating release notes for multiple builds/stages, we nest the related pages in our wiki: 
```
Release Notes
	\ Project 1
		v1
		v2
		...
	\ Project 2
		v1
		v2
		...
	\ Project 3
		v1
		v2
		...
```

When using the `updateOrderFile` option, only the `.order` file at the root of the wiki repo is updated, which does not influence the order of the pages in any of the subfolders.

### Describe the solution you'd like

A new option that controls the placement of new pages in the respective subfolder. In our case, that would result in:
```
Release Notes
	\ Project 1
		v2
		v1
		...
	\ Project 2
		v2
		v1
		...
	\ Project 3
		v2
		v1
		...
```

### Describe alternatives you've considered

The desired functionality can also be implemented with a custom powershell/bash script - but now you're forced to interact directly with a second git repository in your script, which isn't ideal.

**Comment by rfennell** [comment]
Is it reasonable to require you to use a new parameter to pass in the path to the `.order` file you with to update e.g.

```yml
- task: WikiFolderUpdaterTask@1
  inputs: 
     # other arguments...
     updateOrderFile: true 
     orderFilePath: /project1/v1
```

if this new parameter was not set the file on the root will be used, as now

**Comment by rfennell** [comment]
Just publishing the updated version now. The new usage is

````
            - task: WikiUpdaterTask@1
              displayName: 'Git based WIKI Updater - Azure DevOps with Creds update TestFolder/.order file'
              inputs:
                repo: 'dev.azure.com/richardfennell/Git%20project/_git/Git-project.wiki'
                filename: TestFolder/TestPageWithCreds-$(build.buildid).md
                contents: |
                  Header
                  ---
                  $(OutputText)
                  ---
                  Footer
                message: 'Update from Release - $(Release.ReleaseName) with Creds'
                gitname: builduser
                gitemail: 'build@demo'
                user: richardfennell
                password: '$(AzureDevOpsPAT)'
                localpath: '$(System.DefaultWorkingDirectory)\azurerepowithcreds'
                updateOrderFile: true
                orderFilePath: "TestFolder"
````

**Comment by johanndev** [comment]
Awesome, thank you so much!

**Comment by johanndev** [comment]
@rfennell 
Unfortunately, my first test of the new feature was unsuccessful :/

Log output:
```
Starting: WikiUpdaterTask
==============================================================================
Task         : Git based WIKI Single File Updater from Black Marble
Description  : A tools to update or create a file in a WIKI based in a Git repo 
Version      : 1.35.4
Author       : Richard Fennell
Help         : Version: 1.35.4. [More Information](https://github.com/rfennell/vNextBuild/wiki/Wiki-Updater-Task/)
==============================================================================
Variable: Repo [https://<org>@dev.azure.com/<org>/<project>/_git/<project>.wiki]
Variable: Filename [Release/test/myNewWikiPage.md]
Variable: Contents [undefined]
Variable: Commit Message [Update release notes for myNewWikiPage]
Variable: Git Username [9de84241-6340-6dfa-8158-98aefae37ada]
Variable: Git Email [<name>@<org>]
Variable: Use Agent Token [true]
Variable: Replace File [false]
Variable: Append to File [false]
Variable: Username [undefined]
Variable: Password [*****]
Variable: LocalPath [/home/vsts/work/1/s\repo]
Variable: Data Is File [true]
Variable: SourceFile [myNewWikiPage.md]
Variable: Tag Repo [false]
Variable: Tag [undefined]
Variable: Branch [wikiMaster]
Variable: InjectExtraHeader [false]
Variable: Retries [5]
Variable: trimLeadingSpecialChar [false]
Variable: fixLineFeeds [true]
Variable: fixSpaces [false]
Variable: insertLinefeed [false]
Variable: updateOrderFile [true]
Variable: prependEntryToOrderFile [true]
Variable: orderFilePath [Release/test]
Using OAUTH Agent Token, overriding username and password
The provided repo URL is https://<org>@dev.azure.com/<org>/<project>/_git/<project>.wiki
The protocol is https
The provided repo URL is https://<org>@dev.azure.com/<org>/<project>/_git/<project>.wiki
Removing leading http:// or https:// block
Removing leading username@ block
Trimmed the URL to dev.azure.com/<org>/<project>/_git/<project>.wiki
URL used https://buildagent:***@dev.azure.com/<org>/<project>/_git/<project>.wiki
Cleaned /home/vsts/work/1/s\repo
Cloned dev.azure.com/<org>/<project>/_git/<project>.wiki to /home/vsts/work/1/s\repo
Set GIT values in /home/vsts/work/1/s\repo
Creating the directory /home/vsts/work/1/s\repo/Release/test
Checking out the requested branch wikiMaster
Pull in case of post clone updates from other users
Working file name is myNewWikiPage.md
Prepending to the myNewWikiPage.md in /home/vsts/work/1/s\repo/Release/test
Added Release/test/myNewWikiPage.md to repo /home/vsts/work/1/s\repo
Using the file - /home/vsts/work/1/s\repo/Release/test/.order
Creating a new .order file
Preppending entry to the .order file
##[error]Error: fatal: pathspec '/home/vsts/work/1/s\repo/Release/test/.order' did not match any files

##[error]Error: fatal: pathspec '/home/vsts/work/1/s\repo/Release/test/.order' did not match any files

Finishing: WikiUpdaterTask
```

The error occurs during [adding of the new .order file](https://github.com/rfennell/AzurePipelines/pull/1303/files#diff-24491c1a51dff38b84ec4b9191647dce228837741a2c15ebe6760a2718caaba4R267), but I couldn't figure out *why* the error occurs.

**Comment by rfennell** [comment]
Ok, I have a repo of the problem. The problem only occurs if 

- The agent is running Linux
- The folder you are creating the .order file in does not exist

I suspect the issue is related to the `\` in 

> ##[error]Error: fatal: pathspec '/home/vsts/work/1/s\azurerepowithcreds/TestFolder1/.order' did not match any files

Working on a fix

**Comment by rfennell** [comment]
Ah, found it, if the .order files does not exist and prepend is selected nothing is written out - hence the error.

Push a fix out now

**Comment by rfennell** [comment]
Fixed in 1.36.2 - thanks for pointing it out

**Comment by johanndev** [comment]
Thanks you again :)

**Comment by johanndev** [comment]
@rfennell It's me again :)

There is a small issue left - When using the the new `orderFilePath` option, the paths in the `.order` file have to be adjusted from fully-qualified to just the filename, otherwise the ordering does not work.

Example of my task configuration:
```yaml
filename: path/to/release-notes.md
orderFilePath: path/to
prependEntryToOrderFile: true
```

This produces an `.order` file under `path/to` with the content:
```yaml
path/to/release-notes.md
<another-entry>.md
<another-entry>.md
...
```
This is incorrect, the entry is not placed in the front of the list in the wiki file tree. For ordering to work, the entries must only contain the filename, like so:
```yaml
release-notes.md
<another-entry>.md
<another-entry>.md
...
```

Fix should be easy ([see here](https://github.com/rfennell/AzurePipelines/blob/main/Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts#L230)):
```typescript
if (orderFilePath && orderFilePath.length > 0 ) {
    orderFile = `${localpath}/${orderFilePath}/.order`;
    entry = path.basename(entry); // <--- Add this line
}
```
