### ISSUE TITLE
Non UTF-8 characters coming as question marks

### ISSUE THREAD

**Issue by lukasportal** [rfennell/AzurePipelines#1316]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Azure DevOps Server (TFS) Version

windows-latest

### Extension Version

3.83.2

### Describe the bug

The file encoding is not saved as UTF-8 and therefore, the special characters are saved as question marks �

In many languages we have characters like 'á' and this comes out as � without the proper encoding
There's no option to set the encoding to the output file

### Repo Steps

Simply have the output file contain any special characters like 'á'

**Comment by rfennell** [comment]
The output file should be written using UTF8 (See [ReleaseNoteFunctions.ts](https://github.com/rfennell/AzurePipelines/blob/main/Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts) line 1072).

I do have a test for UTF8 writing to a WIKI

![image](https://user-images.githubusercontent.com/324718/182140116-692fd269-bd62-4860-bc4b-a7b4535d0c19.png)

So, have I missed a prepend/append  edge case, what settings are you using?

Also, can I confirm the 'á' not coming from the template, but as a detail of a WI or Commit?

**Comment by lukasportal** [comment]
It’s coming from a commit messageI have the template to only list the commit messages and nothing else  From: Richard FennellSent: Monday, August 1, 2022 12:39 PMTo: rfennell/AzurePipelinesCc: Lucas Souza; AuthorSubject: Re: [rfennell/AzurePipelines] Non UTF-8 characters coming as question marks (Issue #1316) The output file should be written using UTF8 (See ReleaseNoteFunctions.ts line 1072).I do have a test for UTF8 writing to a WIKISo, have I missed a prepend/append edge case, what settings are you using?Also, can I confirm the 'á' not coming from the template, but as a detail of a WI or Commit?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by rfennell** [comment]
That is something to work with, my test case had the UTF8 character in a WI title. I will do some testing

**Comment by rfennell** [comment]
Ok I have done this test

1. Create a new commit with the commit message of `Updated with UTF8 with a á`
2. Push the commit and a build has run that includes my task (I have also tested using my [command line tester](https://github.com/rfennell/AzurePipelines/tree/main/Extensions/XplatGenerateReleaseNotes/V3/testconsole) which allows we generate release notes without the need to run a pipeline) using the template

```
## Global list of WI ({{workItems.length}})
{{#each_with_sort_by_field   workItems "System.Tags"}}
{{#if isFirst}}## Associated Work Items (only shown if  WI) {{/if}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
   - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
   - **Tags** {{lookup this.fields 'System.Tags'}}
   - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
{{/each_with_sort_by_field  }}


## Global list of CS ({{commits.length}})
{{#forEach commits}}
* **{{truncate this.id 7}}** {{this.message}}
{{/forEach}}](url)

```

and the yaml

```YAML
- task: XplatGenerateReleaseNotes@3
  inputs:
    outputfile: '$(Build.ArtifactStagingDirectory)/releasenotes.md'
    templateLocation: 'File'
    templatefile: '$(System.DefaultWorkingDirectory)/template.md'
    dumpPayloadToConsole: false
    dumpPayloadToFile: false
    replaceFile: true
    customHandlebarsExtensionFile: 'custom.js'
    customHandlebarsExtensionFolder: '$(System.DefaultWorkingDirectory)'
    getParentsAndChildren: false
    getAllParents: false
    getIndirectPullRequests: true
    stopOnError: false
    considerPartiallySuccessfulReleases: false
    checkForManuallyLinkedWI: false
```

3. Check the exported output file and it has the UTF8 characters

> ## Global list of WI (0)
> 
> 
> ## Global list of CS (1)
> * **8124aae** Updated with UTF8 with a á


So I am obviously doing some thing different to you, can you see the difference?
