### ISSUE TITLE
WikiUpdater duplicates old text at start and end

### ISSUE THREAD

**Issue by wizgob** [rfennell/AzurePipelines#1340]
### Azure DevOps Extensions

WIKI Updater

### Platform

Azure DevOps Services

### Extension Version

1.41.5

### Describe the bug

We are using the WikiUpdater task to update a change log in a wiki.
We are prepending new text to the existing page.

Now instead of getting:
"New text"
"Old text"

We get:
"Old text"
"New text"
"Old text"

### Repo Steps

Azure pipe YAML for the task

```
- task: WikiUpdaterTask@1
  inputs:
    repo: 'https://example.visualstudio.com/Project/_git/Documentation'
    filename: 'ReleaseNotes.md'
    message: 'Publish release notes $(Build.BuildNumber)'
    gitName: 'BuildService'
    gitEmail: 'build@example.com'
    dataIsFile: True
    sourceFile: '$(Agent.TempDirectory)\ReleaseNotes.md'
    replaceFile: False
    appendToFile: False
    useAgentToken: True
```
