### ISSUE TITLE
TOC replacement fails due to carriage retrun

### ISSUE THREAD

**Issue by mleneveut** [rfennell/AzurePipelines#1350]
### Azure DevOps Extensions

WIKI Updater

### Platform

Azure DevOps Services

### Extension Version

1.42.4

### Describe the bug

When using 

appendToFile: false
injecttoc: true

The old [[_TOC_]] is not removed.

I think it's because the line contains [[_TOC_]]\n and not [[_TOC_]]\r\n

The WIKI file is created and sometimes edited with the UI :  
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/3854415/192266287-bcaa62d5-84bb-4926-aae2-7ddb0f14568f.png">

### Repo Steps

```
- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks.WikiUpdaterTask.WikiUpdaterTask@1
  displayName: 'Generate Wiki page'
  inputs:
    repo: 'https://dev.azure.com/XXX/_git/repo.wiki'
    filename: 'Release-Note-Energy-Billing.md'
    dataIsFile: false
    contents: $(RNContent)
    message: 'Updated the energy billing Release Notes with version $(tagVersion)'
    gitname: 'Project Collection Build Service'
    gitemail: 'XXX'
    useAgentToken: true
    trimLeadingSpecialChar: true
    fixLineFeeds: false
    insertLinefeed: true
    appendToFile: false
    replaceFile: false
    injecttoc: true
```

### Expected Behavior

The previous TOC is remove and replaced with a new one.

### Logging Information

Variable: Username [undefined]
Variable: Password [*****]
Variable: LocalPath [D:\a\1\s\repo]
Variable: Data Is File [false]
Variable: SourceFile [undefined]
Variable: Tag Repo [false]
Variable: Tag [undefined]
Variable: Branch [undefined]
Variable: InjectExtraHeader [false]
Variable: SslBackend [undefined]
Variable: Retries [5]
Variable: trimLeadingSpecialChar [true]
Variable: fixLineFeeds [false]
Variable: fixSpaces [false]
Variable: insertLinefeed [true]
Variable: updateOrderFile [false]
Variable: prependEntryToOrderFile [false]
Variable: orderFilePath [undefined]
Variable: injecttoc [true]
Using OAUTH Agent Token, overriding username and password
The provided repo URL is https://dev.azure.com/XXX/_git/repo.wiki
The protocol is https
The provided repo URL is https://dev.azure.com/XXX/_git/repo.wiki
Removing leading [http://](http:) or [https://](https://github.com/rfennell/AzurePipelines/issues/new?assignees=&labels=bug&template=bug_report.yaml) block
Trimmed the URL to dev.azure.com/XXX/_git/repowiki
URL used https://buildagent:***@dev.azure.com/XXX/_git/repo.wiki
Cleaned D:\a\1\s\repo
Cloned dev.azure.com/mylight-systems-solutions/MyLight%20V3/_git/repo.wiki to D:\a\1\s\repo
Set GIT values in D:\a\1\s\repo
Pull in case of post clone updates from other users
Working file name is Release-Note-Energy-Billing.md
Prepending to the Release-Note-Energy-Billing.md in D:\a\1\s\repo\Release-notes
Added Release-Note-Energy-Billing.md to repo D:\a\1\s\repo
Committed file "D:\a\1\s\repo" with message "Updated the energy billing Release Notes with version 1.0.0" as SHA 87d642d
Attempt 1 - Push to dev.azure.com/XXX/_git/repo.wiki
Push completed
Finishing: Generate Wiki page
