### ISSUE TITLE
The field `wiqlWhereClause` not working

### ISSUE THREAD

**Issue by MatheusXavier** [rfennell/AzurePipelines#1363]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Describe the bug

I'm running the task Generate Release Notes in Azure DevOps using the following configuration:
```
- task: XplatGenerateReleaseNotes@3
   inputs:
     outputfile: "$(System.DefaultWorkingDirectory)/ReleaseNotes.md"
     templateLocation: "InLine"
     inlinetemplate: |
       # Work Items delivered
       {{#forEach workItems}}
       - **{{this.id}} - {{lookup this.fields 'System.WorkItemType'}}:** {{lookup this.fields 'System.Title'}}
       {{/forEach}}
     dumpPayloadToConsole: false
     dumpPayloadToFile: false
     replaceFile: false
     getParentsAndChildren: False
     appendToFile: true
     getAllParents: False
     getIndirectPullRequests: False
     stopOnError: False
     considerPartiallySuccessfulReleases: False
     checkForManuallyLinkedWI: False
     wiqlFromTarget: "WorkItems "
     wiqlWhereClause: "[System.State] = 'Done' AND ([System.WorkItemType] = 'Product Backlog Item' OR [System.WorkItemType] = 'Bug')"
   displayName: Generate release notes
```
I want to generate the release notes only with items of type **Product Backlog Item** and **Bugs** that are in **Done** state, so I'm using the `wiqlWhereClause` to help me with this filter but it's not working because some items with type Task and State InProgress are being listed.

### Repo Steps

1. Create a new pipeline with the provided configuration in the bug description
2. Associate some Work Items to this branch
3. Run the pipeline
4. All related items are being listed

### Expected Behavior

Should generate a new Release Notes only with Work Items of type **Product Backlog Item** or **Bug** with state **Done**
