### ISSUE TITLE
Commit changes path filter

### ISSUE THREAD

**Issue by florianbader** [rfennell/AzurePipelines#1425]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Is your feature request related to a problem? Please describe.

The release notes generator in a mono repository with multi-stage YAML pipeline is not working as intended because the Azure DevOps API that determines the changes between two builds is returning commits that are not relevant to the pipeline.

Example repo structure:
```
/eng/app1/pipeline.yml
/eng/app2/pipeline.yml
/projects/app1/Program.cs
/projects/app2/Program.cs
```

pipeline.yml
```yaml
trigger:
  batch: false
  branches:
    include:
      - main
  paths:
    include:
      - projects/project1/*
      - eng/project1.yml
      
stages:
...
  - task: XplatGenerateReleaseNotes@3
    inputs:
      outputfile: "$(Build.ArtifactStagingDirectory)/releasenotes.md"
      templateLocation: "File"
      templatefile: "$(System.DefaultWorkingDirectory)/eng/template.hbs"
      checkStage: true
``` 

This checks the commits that happened between the last successful pipeline run of the stage and the current. 

Take the following commit history
```
003 Change app1/Program.cs (# 15) 
002 Change app2/Program.cs (# 14) 
001 Change app1/Program.cs (# 13)
```

App 1 pipeline
```
1.1 Run app1 pipeline successfully for stage1 (commit 003)
1.0 Run app1 pipeline successfully for stage1 (commit 001)
```

App 2 pipeline
```
1.0 Run app2 pipeline successfully for stage1 (commit 002)
```

The app 1 pipeline run 1.1 now contains the commits 002 and 003 but actually only in commit 003 something changed that triggered the pipeline. Because the two commits are included it also includes the two work items (14 and 15) and associated pull requests.

### Describe the solution you'd like

Actually this could be filtered out the same way the CI trigger works: by specifying a file filter (glob pattern) to the release notes. That way the task can filter all commits that have no changes within the specified paths which in turn also filters out the wrongly assigned pull requests and work items.

```yaml
  - task: XplatGenerateReleaseNotes@3
    inputs:
      outputfile: "$(Build.ArtifactStagingDirectory)/releasenotes.md"
      templateLocation: "File"
      templatefile: "$(System.DefaultWorkingDirectory)/eng/template.hbs"
      checkStage: true
      includeChanges:
        - projects/project1/**/*
        - eng/project1.yml
```

Just to be complete in both ways an exclude filter could also be useful:

```yaml
  - task: XplatGenerateReleaseNotes@3
    inputs:
      outputfile: "$(Build.ArtifactStagingDirectory)/releasenotes.md"
      templateLocation: "File"
      templatefile: "$(System.DefaultWorkingDirectory)/eng/template.hbs"
      checkStage: true
      includeChanges:
        - projects/project1/**/*
        - eng/project1.yml
     excludeChanges:
        - **/*.md
```
