### ISSUE TITLE
TargetFolder and SourceFolder parameters showing invalid argument type

### ISSUE THREAD

**Issue by sofia-valles** [rfennell/AzurePipelines#1461]
I am trying to use the wiki updater task for multiple files (https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-WIKIUpdater-Tasks&ssr=false#overview). However when I pass the paths to the TargetFolder and SourceFolder parameters which are strings, I get an invalid argument type error: ##[error]TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined.

Here is my task:
```
- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks.WikiUpdaterTask.WikiUpdaterTask@1
                  displayName: "Git based WIKI as code Updater"
                  inputs:
                    repo: "dev.azure.com/organization/project/_git/wikiname.wiki"
                    targetFolder: "Documentation"
                    sourceFolder: "$(System.DefaultWorkingDirectory)/Repo/Documentation"
                    message: "Update markdowns in wiki"
                    username: "username"
                    password: $(personalAccessToken)
```
Here is a screenshot of the error:
![image](https://user-images.githubusercontent.com/47556305/212892399-805b76b4-a0a4-4660-90cd-191cfec6b602.png)

**Comment by rfennell** [comment]
My tests uses the following parameters

```yaml
- task: richardfennellBM.BM-VSTS-WIKIUpdaterTasks-DEV.WikiUpdaterTask.WikiUpdaterTask@2
  displayName: 'Git based WIKI Updater - Readme'
  inputs:
    repo: '${{parameters.repo}}'
    filename: '${{parameters.wikiFilename}}.md'
    dataIsFile: true
    sourceFile: '${{parameters.workingDirectory}}/out/${{parameters.wikiFilename}}.md'
    message: 'Update the ${{parameters.wikiFilename}} Release Notes Readme'
    gitname: '${{parameters.GitName}}'
    gitemail: '${{parameters.GitEmail}}'
    user: '${{parameters.UserName}}'
    password: '${{parameters.GitHubPat}}'
```

This task uploads a single file to the wiki git repo, in this case injecting the contents passed. SO I think the issue you have not specified a filename

**Comment by sofia-valles** [comment]
@rfennell Yes it works fine for a single file but if I want to make use of the multi file feature as pictured on the market place, I get the error mentioned above:
![image](https://user-images.githubusercontent.com/47556305/213135920-6b5bb75e-bc4c-4c94-a84c-2b428615536e.png)

**Comment by rfennell** [comment]
Sorry, I misunderstood. The task you are using is for a single file, to upload multiple files there is a multi file task in the same extension package.

It's usage is as follows, basically you pass a folder and a filter

```yaml
            - task: WikiFolderUpdaterTask@2
              inputs:
                repo: 'dev.azure.com/richardfennell/GitHub/_git/GitHub.wiki'
                targetFolder: 'folder'
                replaceFile: True
                sourceFolder: '$(Build.SourcesDirectory)/testdata'
                Filter: '**/*.md'
                message: 'Updated as a folder'
                gitname: builduser
                gitemail: 'build@demo'
                useAgentToken: true
                localpath: '$(System.DefaultWorkingDirectory)\azurerepoasagentfolder'
```
