### ISSUE TITLE
0 files found in sourceFolder wiki folder updater

### ISSUE THREAD

**Issue by sofia-valles** [rfennell/AzurePipelines#1464]
### Azure DevOps Extensions

WIKI Updater

### Platform

Azure DevOps Services

### Describe the bug

I use a PS script which generates md files from bicep files located in a folder in my repository. After this I want to update the devops wiki using the WikiFolderUpdaterTask.  However, the task is unable to find files in the source folder which contains the md files.

The variables in this pipeline are:
```
variables:
          - name: acr
            value: crazcoresupwes001
          - name: modulesFolder
            value: "$(System.DefaultWorkingDirectory)/CodeRegistry/Modules"   
          - name: markdownFolder
            value: "$(System.DefaultWorkingDirectory)/CodeRegistry/Documentation"
```

My tasks are:
```
- task: PowerShell@2
  displayName: 'Docs - Generate scripts documentation'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/CodeRegistry/Pipelines/create-md-documentation.ps1'
    arguments: -TemplateFolder $(modulesFolder) -OutputFolder $(markdownFolder) -PAT $(personalAccessToken)
    pwsh: true
                
- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks.WikiFolderUpdaterTask.WikiFolderUpdaterTask@2
  displayName: "Git based WIKI as code Updater"
  inputs:
    repo: 'dev.azure.com/org/repo/_git/wikiname.wiki'
    targetFolder: "Documentation"
    replaceFile: true
    sourceFolder: $(markdownFolder)
    Filter: 'acr.md'
    message: 'Update markdowns in wiki'
    username: 'AzureFoundation'
    password: $(personalAccessToken)
```

### Repo Steps

Run the pipeline which contains the mentioned tasks

### Expected Behavior

The task should detect the md files located in the source folder. Then the wiki should be updated with those files.

### Logging Information

Logs of the PS task -> notice that D:\a\1\s\CodeRegistry\Documentation indeed contains the generated md files.
![image](https://user-images.githubusercontent.com/47556305/213400130-8fa83ca7-4924-4e6f-aeb4-7d746d14d823.png)

![image](https://user-images.githubusercontent.com/47556305/213398332-29c7d2bf-2193-424e-98c1-633138c25baf.png)
Content of the outputfolder: D:\a\1\s\CodeRegistry\Documentation\.order D:\a\1\s\CodeRegistry\Documentation\acr.md D:\a\1\s\CodeRegistry\Documentation\keyvault.md D:\a\1\s\CodeRegistry\Documentation\resourceGroup.md D:\a\1\s\CodeRegistry\Documentation\storageAccount.md

The result of the wiki folder updater task:
![image](https://user-images.githubusercontent.com/47556305/213401052-35abdf2b-c50d-4273-acac-a2eeac331f13.png)
