### ISSUE TITLE
Working Items are not showing up - Xplathtemplate

### ISSUE THREAD

**Issue by Quallos** [rfennell/AzurePipelines#1542]
Hello!

Sorry I am a bit new to handlebar templates and also azure pipeline.

I am trying to figure out how to get workitems inside of my template.

This is a snippet of my template:

`
XXX API TITLE
Release Notes for {{buildDetails.buildNumber}}
These are the most updated Workitems
Total Number of Work Items: {{workItems.length}}
`

It returns 0 which is not true.

Here is a piece of my logs inside the pipeline:

Loading template file /opt/vsts_agent/_work/1/s/xxxxxx.md
##[debug]Loading handlebar template
##[debug]Processing template
##[debug] WI: 0
##[debug] CS: 1
##[debug] PR: 0
##[debug] Builds: 0
##[debug] Manual Tests: 0
##[debug] Manual TestConfigurations: 0
##[debug] Release Tests: 0
##[debug] Related WI: 0
##[debug] Related Tests: 0
##[debug] Indirect PR: 0
##[debug] Consumed Artifacts: 0
##[debug] Published Artifacts: 0
##[debug] Query WI: 13
##[debug]Processing handlebar template
Loading handlebars-helpers extension

Here is my Task Setup

```
      - task: XplatGenerateReleaseNotes@4
        displayName: 'Generate Release Notes'
        inputs:
          outputfile: '$(Build.BuildNumber).md'
          templateLocation: 'File'
          templatefile: 'xxxx-docs/templates/xxxxxx.md'
          dumpPayloadToConsole: false
          dumpPayloadToFile: false
          replaceFile: true
          getParentsAndChildren: false
          getAllParents: false
          getIndirectPullRequests: false
          checkstages: true
          failOnStderr: true
          wiqlSharedQueryName: Range 10500-10999/XXXX/XXXX
          checkForManuallyLinkedWI: true
```
