### ISSUE TITLE
WikiPDFExport: Cannot find the requested file xx to export

### ISSUE THREAD

**Issue by ph1f1** [rfennell/AzurePipelines#1573]
### Azure DevOps Extensions

WIKI PDF Generator

### Platform

Azure DevOps Server (TFS) - Specify Version

### Azure DevOps Server (TFS) Version

Azure DevOps Server 2022

### Extension Version

3.*

### Describe the bug

I did setup the task in a Release Pipeline and it works as long as o don't provide a Filename in the "Single file to export" option.
As soon as I put a filename in there, the error "Cannot find the requested file xx to export" is shown and it fails.

I double and tripple checked, if the file is in the artifacts folder of the release agent- it definitly is.

An odd behaviour also occurs if I export the whole Wiki to the pdf. All files but the "leaves" of the folder tree get generated into the pdf. I'm not sure, if this has anything to do with the my problem.

Example folder structure where Home.md and Versions.md will be included, but ReleaseNotes_Release-39.md not:
- File Home.md
- Folder Home
  - File Versions.md
  - Folder Versions
    - ReleaseNotes_Release-39.md

Configuration of the Task:
```
variables:
  ReleaseNotesPdfFileName: 'ReleaseNotes.pdf'

steps:
- task: richardfennellBM.BM-VSTS-WikiPDFExport-Tasks.WikiPDFExportTask.WikiPdfExportTask@3
  displayName: 'Create PDF from Wikipage'
  inputs:
    cloneRepo: false
    singleFile: 'ReleaseNotes_Release-95.md'
    useAgentToken: true
    localpath: '$(System.DefaultWorkingDirectory)\wikiRepo'
    rootExportPath: '$(System.DefaultWorkingDirectory)\wikiRepo\Home\Versions'
    outputFile: '$(System.DefaultWorkingDirectory)\$(ReleaseNotesPdfFileName)'
    injectExtraHeader: true
```

What am I missing?

### Logging Information

2023-12-04T10:44:02.1533564Z URL used https://xxx.xxx.xxx/DefaultCollection/SU/_git/SU.wiki
2023-12-04T10:44:02.2212486Z Cleaned C:\azagent\agent2\_work\r50\a\wikiRepo
2023-12-04T10:44:03.3620611Z Cloned xxx.xxx.xxx/DefaultCollection/SU/_git/SU.wiki to C:\azagent\agent2\_work\r50\a\wikiRepo
2023-12-04T10:44:03.3633928Z A filename 'ReleaseNotes_Release-94.md' in the folder 'C:\azagent\agent2\_work\r50\a\wikiRepo\Home\Versions' has been requested so only processing that file 
2023-12-04T10:44:03.3700566Z ##[error]Cannot find the requested file ReleaseNotes_Release-94.md to export
2023-12-04T10:44:03.3713474Z ##[debug]Processed: ##vso[task.issue type=error;]Cannot find the requested file ReleaseNotes_Release-94.md to export
2023-12-04T10:44:03.3714797Z ##[debug]task result: Failed
2023-12-04T10:44:03.3716187Z ##[error]Cannot find the requested file ReleaseNotes_Release-94.md to export
2023-12-04T10:44:03.3717362Z ##[debug]Processed: ##vso[task.issue type=error;]Cannot find the requested file ReleaseNotes_Release-94.md to export
2023-12-04T10:44:03.3719961Z ##[debug]Processed: ##vso[task.complete result=Failed;]Cannot find the requested file ReleaseNotes_Release-94.md to export
2023-12-04T10:44:03.4250591Z ##[section]Finishing: Create PDF from Wikipage

**Comment by rfennell** [comment]
I think I have made a poor explanation of the `rootExportPath` parameter in the WIKI

Looking at the code I think these are the parameters you are

```yaml
task: richardfennellBM.BM-VSTS-WikiPDFExport-Tasks.WikiPDFExportTask.WikiPdfExportTask@3
displayName: 'Create PDF from Wikipage'
inputs:
cloneRepo: false
useAgentToken: true
localpath: '$(System.DefaultWorkingDirectory)\wikiRepo'
rootExportPath: '$(System.DefaultWorkingDirectory)\wikiRepo\Home\Versions\ReleaseNotes_Release-95.md'
outputFile: '$(System.DefaultWorkingDirectory)$(ReleaseNotesPdfFileName)'
injectExtraHeader: true
```

There is no need to specific the file as parameter it should be part of `rootExportPath`. 

Let me know if this works for you, if it does I will improve the documentation and I think alter the code so the way you were working would also work, I can see it is a very easy mistake to make
