### ISSUE TITLE
How can we get the WorkItems triggered from different repos(same project) details when associated with PR

### ISSUE THREAD

**Issue by pchaploutskii** [rfennell/AzurePipelines#2075]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Extension Version

4.22.4

### Describe the bug

Not able pull WI associated with PR with in build pipeline
```
trigger: none

resources:
  repositories:
  - repository: repo_web
    type: git
    name: Repo.Web
    trigger:
      - main
      - release
  - repository: repo_backend
    type: git
    name: Repo.Backend
    trigger:
      - main
      - release
     
....

- task: XplatGenerateReleaseNotes@4
  inputs:
    outputfile: '$(System.DefaultWorkingDirectory)/release-notes-template.md'
    templateLocation: 'InLine'
    inlinetemplate: |  
      ## Associated Pull Requests ({{pullRequests.length}})
      {{#forEach pullRequests}}
      * **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
      * Associated Work Items
        {{#forEach this.associatedWorkitems}}
          {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
            - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}}
          {{/with}}
        {{/forEach}}
        * Associated Commits (this s commits on the PR source branch not associated directly with the build)
        {{#forEach this.associatedCommits}}
            - [{{this.commitId}}]({{this.remoteUrl}}) -  {{this.comment}}
        {{/forEach}}
      {{/forEach}} 
    sortCS: false
    dumpPayloadToConsole: true
    dumpPayloadToFile: false
    replaceFile: true
    getParentsAndChildren: true
    getAllParents: true
    getIndirectPullRequests: true
    stopOnError: false
    considerPartiallySuccessfulReleases: true
    overrideExistingReleaseNotes: true
    getCompareBranch: true
    getMostRecentRelease: true
    checkForManuallyLinkedWI: true
    generateHistoryFromLastRelease: true
    treatProjectNameAsVariable: true
    getWorkItems: true
    getTestCases: true
    checkStage: true
```

confirm related WI with in the build
<img width="210" alt="Image" src="https://github.com/user-attachments/assets/1d409060-2c46-4c22-9502-59d00631b3d9" />
also I can pull WI via API call
ProjectName/_apis/git/repositories/Repo.Web/pullRequests/1/workitems?api-version=7.0
Same output in [Command line tester](https://github.com/rfennell/AzurePipelines/tree/main/Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/testconsole)

The issue only affects resource repositories and does not impact the repository where the pipeline is stored. 
Tried On and Off settings discussed w/[similar issue](https://github.com/rfennell/AzurePipelines/issues/1565#issuecomment-1851375228)

### Repo Steps

Go to '...'
Click on '....'
Scroll down to '....'
See error

### Logging Information

Enriching known Pull Requests
Checking the CS associated with the PRs to see if they are inturn associated PRs
Total Builds: [0]
Total Commits: [2]
Total Workitems: [0]
Total Related Workitems (Parent/Children): [0]
Total Release Tests: [0]
Total Tests: [0]
Total Manual Test Runs: [0]
Total Manual Test Configurations: [0]
Total Pull Requests: [0]
Total Indirect Pull Requests: [0]
Total Associated Test WI: [0]
Total Published Artifacts: [0]
Total Consumed Artifacts: [2]
Total WIQL Workitems: [0]
Start of payload data dump

**Comment by rfennell** [comment]
First step is to get a detailed log, you can get this from the Local tester, or run the pipeline with the variable `system.debug=true`.

This will show the discovery process the task is using, that might show an issue

**Comment by pchaploutskii** [comment]
From the local tester, working build Id 2044 triggered at change in repo_web, and 2042 is change with azure-pipeline.yml is:
```
Getting WI associated with builds between 1993 to 2044 to make sure we find ones manually linked to build
##vso[task.debug]Checking build 2044 found 0 WI
##vso[task.debug]Checking build 2043 found 0 WI
##vso[task.debug]Checking build 2042 found 1 WI
##vso[task.debug]Checking build 2041 found 0 WI
```
PAT configured - full access

**Comment by pchaploutskii** [comment]
Thank you for the detailed explanation; I really appreciate it.
So far, I've been calling:
`$baseUrl/_apis/git/repositories/$(Build.Repository.ID)/pullRequests/$(pr_Id)/workitems?api-version=7.0`
 This successfully retrieves related work items (WIs) for the build ID which is exactly what I need. Would it be possible to feed this output into a list of WIs?

**Comment by rfennell** [comment]
@pchaploutskii that is good suggestion, I could update the logic to match the PRs to the pipeline by proving an option in place using  the `MergeCommitID` for the match, to just any match with any the PR commit using `$baseUrl/_apis/git/repositories/$(Build.Repository.ID)/pullRequests/$(pr_Id)/commits?api-version=7.0` and then working back to the WI.

I would need to handle both mechanisms as this would be a potentially breaking change in PR association behaviour for some uses.

I will build it on a branch and let you when it is done so you try it in the local tester, see if it does what you need.

**Comment by rfennell** [comment]
@pchaploutskii I have started a PR #2076 that provides a different way to get the associated PRs.

Whilst doing this, I remembered why I had not used this method before, it needs many more API calls, so is slow.

Can you pull down the branch and try it in your local tester environment and see if the performance is at least acceptable in your senario

**Comment by pchaploutskii** [comment]
Thank you for the quick response. I have tested on two builds—build 75 contains one WI, which is correctly reflected in output.md, exactly what I need. However, build 76 has two WIs, yet output.md is empty, even though the console logs ##vso[task.debug] WI: 1

75
```
Getting WI associated with builds between 69 to 75 to make sure we find ones manually linked to build
##vso[task.debug]Checking build 75 found 1 WI
##vso[task.debug]Checking build 74 found 0 WI
##vso[task.debug]Checking build 73 found 0 WI
...
Loading template file build-handlebars-template5.md
##vso[task.debug]Loading handlebar template
##vso[task.debug]Processing template
##vso[task.debug]  WI: 1
##vso[task.debug]  CS: 5
##vso[task.debug]  PR: 1
##vso[task.debug]  Builds: 0
##vso[task.debug]  Manual Tests: 0
##vso[task.debug]  Manual TestConfigurations: 0
##vso[task.debug]  Release Tests: 0
##vso[task.debug]  Related WI: 1
##vso[task.debug]  Related Tests: 0
##vso[task.debug]  Indirect PR: 0
##vso[task.debug]  Consumed Artifacts: 2
##vso[task.debug]  Published Artifacts: 0
##vso[task.debug]  Query WI: 0
```

76
```
Processing commits found
Getting WI associated with builds between 69 to 76 to make sure we find ones manually linked to build
##vso[task.debug]Checking build 76 found 0 WI
##vso[task.debug]Checking build 75 found 1 WI
##vso[task.debug]Checking build 74 found 0 WI
##vso[task.debug]Checking build 73 found 0 WI
...
##vso[task.debug]Loading handlebar template
##vso[task.debug]Processing template
##vso[task.debug]  WI: 1
##vso[task.debug]  CS: 4
##vso[task.debug]  PR: 0
##vso[task.debug]  Builds: 0
##vso[task.debug]  Manual Tests: 0
##vso[task.debug]  Manual TestConfigurations: 0
##vso[task.debug]  Release Tests: 0
##vso[task.debug]  Related WI: 1
##vso[task.debug]  Related Tests: 0
##vso[task.debug]  Indirect PR: 0
##vso[task.debug]  Consumed Artifacts: 2
##vso[task.debug]  Published Artifacts: 0
##vso[task.debug]  Query WI: 0
```

**Comment by pchaploutskii** [comment]
To keep things simple, I have three repositories within the same project:
- Pipeline
- Frontend
- Backend

The Pipeline repo contains azure-pipelines.yml, and it correctly pulls work items (WI) associated with a PR pipeline repo. However, when a PR is triggered from the Frontend or Backend repos via azure-pipelines.yml, the associated work items are not being reflected.

**Comment by rfennell** [comment]
I think I need to build same same setup and explore this one

**Comment by rfennell** [comment]
# Setup

To try to get the bottom of this issue I have built a public test team project https://dev.azure.com/richardfennell/3repotest. It contains

- Pipeline - contains a readme file and a CI base YML template that contains the release notes task
- Frontend - contains a readme file and a CI YML pipeline that uses the base extends template
- Backend - same as Frontend

The CI build does nothing other than run, but using the Release Notes local test harness you can point at a given pipeline run and it will generate the release notes, as if the task had been run in the pipeline. The configuration file is as shown below, you alter 

- line 3 to set the target build
- line 4 to choose the way PRs are detected, as discussed above

```json
{
    "TeamFoundationCollectionUri": "https://dev.azure.com/richardfennell",
    "TeamProject": "3repotest",
    "buildId": "12434",
    "matchPRsByMergeCommit": "false",

    "releaseDefinitionId": "",
    "releaseId": "",
    "environmentName":"_DEFAULT",
    "templatefile": "build-handlebars-template.md",
    "outputfile": "output.md",

    "dumpPayloadToConsole": "false",
    "dumpPayloadToFile": "true",
    "dumpPayloadFileName": "payload.json",

    "templateLocation": "File",
    "inlinetemplate": "",
    "outputVariableName": "no available in this tool",
    "showOnlyPrimary": "false",
    "replaceFile": "true",
    "appendToFile": "false",
    "getParentsAndChildren": "true",
    "getAllParents": "true",
    "searchCrossProjectForPRs": "false",
    "stopOnRedeploy": "false",
    "SortWi": "true",
    "SortCS": "true",
    "customHandlebarsExtensionCodeAsFile": "",
    "customHandlebarsExtensionCode": "",
    "customHandlebarsExtensionFile": "customHandlebars.js",
    "customHandlebarsExtensionFolder": ".\\testconsole",
    "overrideStageName": "",
    "checkStage": "false",
    "Fix349": "true",
    "tags": "",
    "overrideActiveBuildReleaseId":"",
    "overrideBuildReleaseId": "",
    "getIndirectPullRequests": "false",
    "considerPartiallySuccessfulReleases": "false",
    "checkForManuallyLinkedWI": "false",
    "wiqlWhereClause": "",
    "getPRDetails": "true",
    "getPRDetailsRepositoryId": "",
    "getPRDetailsRefName": "",
    "getTestedBy": "true",

    "maxRetries": "3",
    "pauseTime": "5000",

    "stopOnError": "false"
}
```

You run the pipeline with the command

```powershell
node .\GenerateReleaseNotesConsoleTester.js --filename .\build-settings.json --pat <your PAT>
```

# What I Tested
1. On both the frontend I edited in the `readme.md` files
2. Committed the change to a new branch
3. Create a PR, and associated the PR with a WI
4. Completed the PR with a merge commit - this triggered the build https://dev.azure.com/richardfennell/3repotest/_build/results?buildId=12438&view=results
     - Find 1 PR. 1 WI and 2 CS
6. Repeated steps 1 to 3
7. Completed the PR with a squash commit - this triggered the build https://dev.azure.com/richardfennell/3repotest/_build/results?buildId=12439&view=results
     - Find 1 PR. 1 WI and 1 CS

# Question
So I see the behaviour I expect,  @pchaploutskii can tell me how this differs from what you are trying to do?

**Comment by pchaploutskii** [comment]
One difference I have is frontend and backend doesn't have azure-pipeline.yml, for me all Pipeline logic I am storing in one Repository - Pipeline and watch after any changes via:
```
resources:
  repositories:
  - repository: frontend
    type: git
    name: frontend
    trigger:
      - main
      - release
  - repository: backend
    type: git
    name: backend
    trigger:
      - main
      - release
```

The idea for my config is: any changes happens either Frontend or Backend will build everything at once and push Release notes to Wiki.

azure-pipeline.yml
```
trigger: 
  branches:
    include:
      - release

resources:
  repositories:
  - repository: frontend
    type: git
    name: frontend
    trigger:
      - main
      - release
  - repository: backend
    type: git
    name: backend
    trigger:
      - main
      - release
  - repository: wiki_repository
    type: git  
    name: adf.wiki
    ref: wikiMaster

variables:
  system.debug: 'true'

stages:
  - stage: Release_Notes_Wiki
    pool:
      name: 'Optiplex dev agent'
    displayName: 'Compose Release Notes'
    
    jobs:
    - job: buildandpush
      displayName: Reading Parameters

      steps:

      - checkout: wiki_repository
      - checkout: frontend
      - checkout: backend
      - checkout: self
        path: ./build

      - script: |
          pwd
          (a='------------------------------------------------------------'
          echo -e $a
          echo Debugging...
          echo -e $a)
          echo ""
          find ..
        displayName: Debugging

      - task: PowerShell@2
        displayName: 'Construct wiki path'
        inputs:
          targetType: 'inline'
          script: |
            $wikiPath = "Project1/$(Build.BuildNumber)"
            Write-Host "Wiki path: $wikiPath"
            Write-Host "##vso[task.setvariable variable=wikiReleaseNotes]$wikiPath"

      - task: XplatGenerateReleaseNotes@4
        inputs:
          outputfile: '$(System.DefaultWorkingDirectory)/release-notes-template.md'
          templateLocation: 'InLine'
          inlinetemplate: |          
            ## Associated Pull Requests ({{pullRequests.length}})
            {{#forEach pullRequests}}
            * **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** {{this.title}}
            * Associated Work Items
              {{#forEach this.associatedWorkitems}}
                {{#with (lookup_a_work_item ../../relatedWorkItems this.url)}}
                  - [{{this.id}}]({{replace this.url "_apis/wit/workItems" "_workitems/edit"}}) - {{lookup this.fields 'System.Title'}}
                {{/with}}
              {{/forEach}}
              * Associated Commits (this s commits on the PR source branch not associated directly with the build)
              {{#forEach this.associatedCommits}}
                  - [{{this.commitId}}]({{this.remoteUrl}}) -  {{this.comment}}
              {{/forEach}}
            {{/forEach}}          
          sortCS: false
          dumpPayloadToConsole: true
          dumpPayloadToFile: false
          replaceFile: true
          getParentsAndChildren: true
          getAllParents: true
          getIndirectPullRequests: true
          stopOnError: false
          considerPartiallySuccessfulReleases: true
          overrideExistingReleaseNotes: true
          getCompareBranch: true
          getMostRecentRelease: true
          checkForManuallyLinkedWI: true
          generateHistoryFromLastRelease: true
          treatProjectNameAsVariable: true
          getWorkItems: true
          getTestCases: true
          checkStage: true

      - task: WikiUpdaterTask@2
        displayName: 'Update Wiki page'
        inputs:
          repo: 'https://dev.azure.com/joywaves/adf/_git/adf.wiki'
          filename: '$(wikiReleaseNotes).md'
          replaceFile: false
          appendToFile: false
          dataIsFile: true
          sourceFile: '$(System.DefaultWorkingDirectory)/release-notes-template.md'
          message: 'Update Release Notes'
          gitname: 'AzureDevOps Agent'
          gitemail: 'noreply@joywaves.com'
          useAgentToken: true
          localpath: '$(System.DefaultWorkingDirectory)/repo'
          insertLinefeed: true
          prependEntryToOrderFile: false
          injecttoc: false
          RetryMode: 'Pull'
```
