### ISSUE TITLE
How to use the "FileCopy" in my YAML file for Azure Pipelines?

### ISSUE THREAD

**Issue by meriturva** [rfennell/AzurePipelines#430]
### Azure DevOps Extension you are using
File Utilities Build Tasks

### Where are you running it?
- Azure DevOps Service (VSTS) - Only YAML editor available

### Version of Extension/Task
3.2.2

### Expected behaviour and actual behaviour
Extension works as described on  YAML documentation https://github.com/rfennell/AzurePipelines/wiki/File-Copier-Tasks-YAML

But now i'm not able to use it, YAML editor just say `String does not match the pattern of "^AzureVmssDeployment@0$"` . I guess it is related to : https://github.com/rfennell/AzurePipelines/issues/390
and
https://github.com/BMuuN/vsts-assemblyinfo-task/issues/78

i really don't know if it related to a new DevOps configuration or a specific case of task.json definition.

### Steps to reproduce the problem
Just add step to an Azure Pipeline YAML Configuration File

**Comment by rfennell** [comment]
I will need to have a look at this, not sure how fast before I will have time, but it is on the backlog to investigate

**Comment by rfennell** [comment]
Can you give me an example of your YAML.

I would expect the block to be something like

```
steps:
- task: richardfennellBM.BM-VSTS-FileCopier-Tasks.FileCopyTask.FileCopy@3
  displayName: FileCopy
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    targetFolder: '$(SYSTEM.ARTIFACTSDIRECTORY)'

```

So a few points

- What is your YAML?
- If you set a build variable syste.debug=true what logging to do you get?
