### ISSUE TITLE
VersionDotNetCoreAssemblies seems ok but csproj file is not modified

### ISSUE THREAD

**Issue by meriturva** [rfennell/AzurePipelines#494]
### Azure DevOps Extension you are using
VersionDotNetCoreAssemblies@2

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
```
Task         : Version .NET Core Assemblies
Description  : Applies a version to a .NET Core assembly via the .csproj files based on the build number. Based on Microsoft sample from https://msdn.microsoft.com/Library/vs/alm/Build/overview
Version      : 2.12.1
Author       : Black Marble
Help         : Version: 2.12.1. [More Information](https://github.com/rfennell/vNextBuild/wiki/Version-Assemblies-and-Packages-Tasks/)
```

I have this build configuration from more than 6 months without any issue, I really don't know why but now I have problems with VersionDotNetCoreAssemblies task. Seems not to save anymore file after transformation (without any error).

```
pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  buildPlatform: x64
  major: 1
  minor: 1
```

### Steps to reproduce the problem

Here task:

```

- task: VersionDotNetCoreAssemblies@2
  displayName: 'Patch DotNetCore versions'
  inputs: 
     Path: '$(Build.SourcesDirectory)'
     VersionNumber: '$(version)'
     Injectversion: False
     VersionRegex: '\d+\.\d+\.\d+'
     FilenamePattern: '.csproj'
     OutputVersion: OutputedVersion
     AddDefault: true
```

Here log:

```
Source Directory:  d:\a\1\s
Filename Pattern: .csproj
Version Number/Build Number: 1.1.181
Version Filter to extract build number: \d+\.\d+\.\d+
Field to update (all if empty): null
Add default field (all if empty): true
Output: Version Number Parameter Name: OutputedVersion
Inject Version: false
Extracting version number from build number
Extracted Version: 1.1.181
Adding file MyProject.BatchSynch.csproj as is a .NETCore Project
....other projects
Will apply 1.1.181 to 12 files.
Checking if any version fields to update
Getting just the PropertyGroup that contains the version fields
Processing Field Version
Existing Tag: <Version>1.1.5</Version>
Replacement Tag: <Version>1.1.181</Version>
Processing Field VersionPrefix
Processing Field AssemblyVersion
Existing Tag: <AssemblyVersion>1.1.5.0</AssemblyVersion>
Replacement Tag: <AssemblyVersion>1.1.181</AssemblyVersion>
d:\a\1\s\MyProject.BatchSynch\MyProjecto.BatchSynch.csproj - version applied
```

I just added csproj to artifacts output (to be sure) with:
```
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'test' 
    targetPath: 'MyProject.BatchSynch\MyProject.BatchSynch.csproj'
```

And file still with original values:

  ```
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <AssemblyName>MyProject.BatchSynch</AssemblyName>
    <PackageId>MyProject.BatchSynch</PackageId>
    <AssemblyVersion>1.1.5.0</AssemblyVersion>
    <Version>1.1.5</Version>
    <FileVersion>1.1.5.0</FileVersion>
  </PropertyGroup>
```
