### ISSUE TITLE
Document how to intelligently use as a release task

### ISSUE THREAD

**Issue by MikeBazMSFT** [rfennell/AzurePipelines#526]
### Azure DevOps Extension you are using
Generate Release Notes Build Task

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Current public

### Expected behaviour and actual behaviour
Documentation says it's valid for release and build tasks, but it's not clear how to use the generated output in a release task - what's a sane output filename for example in this use case?

**Comment by rfennell** [comment]
Have a look at my one release pipelines, specifically for one for the task itself 

https://dev.azure.com/richardfennell/GitHub/_releaseProgress?_a=release-pipeline-progress&releaseId=1490

- In a build I drop the release notes as an artifact.
- For a release I either
    - Send it as an email, using a marketplace task (the one I use for testing)
    - Or upload it to a wiki or UNC file share (I wrote tasks to do both of these)

**Comment by MikeBazMSFT** [comment]
OK, so you always use the task as a build task to create an artifact, then just pick up the artifact in release?  Just making sure, because I'm not sure what this task would be used for in a release pipeline then?

**Comment by rfennell** [comment]
Originally yes, I used to use this task in a build and use the release notes like any other artifact.

However, I don't do that any more.  I have moved to using my Xplat Release Notes tool, which only works in releases, and has the advantage that it uses the same API calls as the Azure DevOps UI (and works on Windows, Mac and Linux). I do my release notes in releases.

As a release has no 'drop location' I have to put the release notes somewhere myself, so as i said I use other tasks to email it or upload to a some location such as a WIKI.

Publishing the release notes (to a wiki) become a step in the release, just like deploying the APP

**Comment by MikeBazMSFT** [comment]
Thank you again.

Just to be very clear on what you're saying (and implying), for greenfield, the Xplat Release Notes tool is a "better" option at this point, and it's used to create the release notes, put them "somewhere," then the "somewhere" is picked up in a later task to process in whatever desired way?

When I played with this, a relative path seemed to be relative to a specific structure on the build agent, specific to the task - which is of course undocumented and can't be relied on.  So how do you decide where the "somewhere" is in a way that you know will be available across different agent configurations and across tasks, since as you correctly say there's no build drop location?  I think this is the biggest thing that caught me up and led to me opening this issue around documentation in the first place, not knowing what a reasonable folder would be :)

**Comment by rfennell** [comment]
Yes, on greenfield I would go Xplat. I am actually considering deprecating the older PowerShell version, but before I do that I do need to add running in a build support to the Xplat version - Microsoft's move to YAML pipelines is changing what can be done, reducing the difference between build and release, so some complex decisions for me as to futures form my tasks

As to where to store release note in a release. I usually save them in a temp folder on the agent they are running on. 

Some my output directory is something like `$(System.DefaultWorkingDirectory)\inline.md`

But remember, the contents of the file is also outputted a to pipeline variable you get to define e.g. `$(OutputText)`. The only issue with this is that this variable has max size of 32K, so if your release notes are every long you can't use a variable, you have to use the file 

I then, as I have said, use another tasks to copy this file somewhere else e.g send an email, copy to a UNC share (if on prem) or to a Wiki.

An example in YAML where I generate a release notes (using an inline template) then send an email using the pipeline variable for the body text but attaching the release notes files...

```
steps:
- task: richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes-DEV1.XplatGenerate-Release-Notes.XplatGenerateReleaseNotes@2
  displayName: 'Generate Release Notes based on Release Comparision API V2'
  inputs:
    outputfile: '$(System.DefaultWorkingDirectory)\inline.md'
    outputVariableName: OutputText
    templateLocation: InLine
    inlinetemplate: |
     # Release notes 
     ## Notes for release  ${releaseDetails.releaseDefinition.name}    
     **Release Number**  : ${releaseDetails.name}    
     **Release completed** : ${releaseDetails.modifiedOn}     
     **Compared Release Number**  : ${compareReleaseDetails.name}    
     
     ### Associated work items  
     @@WILOOP@@  
     * ** ${widetail.fields['System.WorkItemType']} ${widetail.id} ** Assigned by: ${widetail.fields['System.AssignedTo']}  ${widetail.fields['System.Title']}  
     @@WILOOP@@  
       
     ### Associated commits
     @@CSLOOP@@  
     * **ID ${csdetail.commitId} ** ${csdetail.comment}    
     @@CSLOOP@@

- task: rvo.SendEmailTask.send-email-build-task.SendEmail@1
  displayName: 'Send an email with subject Release notes file from $(Agent.Name)'
  inputs:
    To: 'richard1234@hotmail.co.uk'
    From: 'richard1234@hotmail.co.uk'
    Subject: 'Release notes file from $(Agent.Name) V2'
    Body: '$(OutputText)'
    AddAttachment: true
    Attachment: '$(System.DefaultWorkingDirectory)\inline.md'
    SmtpServer: smtp.sendgrid.net
    SmtpUsername: apikey
    SmtpPassword: '***********************************'


```
