### ISSUE TITLE
Cannot uniquely specify filename with VersionJSONFileTask due to use of endswith

### ISSUE THREAD

**Issue by andyward** [rfennell/AzurePipelines#569]
### Azure DevOps Extension you are using

VersionJSONFileTask 2.2.1.1

### Where are you running it?

- Azure DevOps Service (VSTS)

### Version of Extension/Task

2.2.1.1

### Expected behaviour and actual behaviour

An Angular library project can have both a 'project.json' file - which needs versioning,  and a 'ng-package.json' which does **not**. The current VersionJSONFileTask  _findfiles_ implementation uses 'endswith' to identify files matching the _filenamePattern_ which means its not possible to exclude the file prefixed with 'ng-'

The result is the ng-package.json files get corrupted during versioning.

This is a similar issue to  #490  - a similar regex solution would be useful here.

### Steps to reproduce the problem

``` yaml

- task: VersionJSONFile@2
      inputs:
        Path: '$(Build.SourcesDirectory)/projects/'
        recursion: True
        VersionNumber: '$(Build.BuildNumber)'
        useBuildNumberDirectly: False
        VersionRegex: '\d+\.\d+\.\d+'
        versionForJSONFileFormat: '{1}.{2}.{3}'
        FilenamePattern: 'package.json'
        OutputVersion: 'OutputedVersion'

```
