### ISSUE TITLE
Syntax to add multiple testResultsFiles in YML

### ISSUE THREAD

**Issue by gregdegruy** [rfennell/AzurePipelines#605]
### Azure DevOps Extension you are using
*There are a number of Azure DevOps (VSTS) extension in this repo so please say which one you are using, and if an extension contains multiple tasks which task also*

Pester Test Runner Build Task
Extension details
Run Pester tests without the need to install Pester in with the PMModule folder or in the source repo (Using Pester 3.4.3 or 4.3.1).
Publisher
Richard Fennell (Black Marble)
Installed version
8.13.3 (Latest)
Last updated
Mar 10, 2019 at 8:08 AM EDT

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)

### Version of Extension/Task
*I assume it is the currently public version, if you are using an older version on-premises let me know, but the answer will probably involve upgrading to the currently public version*

### Expected behaviour and actual behaviour
Need syntax to add multiple testResultsFiles in YML

```yml
trigger:
- master

pool:
  vmImage: 'windows-latest'

jobs:
- job: PesterUnitTests
  displayName: Pester Unit Tests
  steps:
  - task: PowerShell@2 
    inputs:
      filePath: 'azpipelines.ps1'
      pwsh: true    
  - task: PublishTestResults@2 
    inputs:
      testResultsFormat: 'NUnit'
      # how to do I add more than file below?
      testResultsFiles: $(System.DefaultWorkingDirectory)\Scripts\PesterTestResults.XML, $(System.DefaultWorkingDirectory)\Scripts\AddNumbersResults.XML
      failTaskOnFailedTests: true
```

### Steps to reproduce the problem
Need syntax to add multiple testResultsFiles in YML

**Comment by rfennell** [comment]
Not site why you have logged this in this project as the YAML you show does not use any of my tasks.

However, I think the answer to your question is just to have multiple PublishResults blocks. 

```
  - task: PublishTestResults@2 
    inputs:
      testResultsFormat: 'NUnit'
      # how to do I add more than file below?
      $(System.DefaultWorkingDirectory)\Scripts\AddNumbersResults.XML
      failTaskOnFailedTests: true
  - task: PublishTestResults@2 
    inputs:
      testResultsFormat: 'NUnit'
      # how to do I add more than file below?
      testResultsFiles: $(System.DefaultWorkingDirectory)\Scripts\PesterTestResults.XML
      failTaskOnFailedTests: true
```

**Comment by gregdegruy** [comment]
Thanks refennell, it looks like to upload multiple `testResultsFiles` I would need to create multiple tasks. Is this correct?

It appears there's no support to a comma separated lists of files to the `testResultsFiles` node in YAML? I thought this would the would possible given this node `testResultsFiles` and not `testResultsFile`.

Also I am using your tasks in my Azure DevOps job

```yml
  - task: PowerShell@2 
    inputs:
      filePath: 'azpipelines.ps1'
      pwsh: true    
  - task: PublishTestResults@2 
    inputs:
      testResultsFormat: 'NUnit'
      # how to do I add more than file below?
      testResultsFiles: $(System.DefaultWorkingDirectory)\Scripts\PesterTestResults.XML, $(System.DefaultWorkingDirectory)\Scripts\AddNumbersResults.XML
      failTaskOnFailedTests: true
```

**Comment by rfennell** [comment]
I had a think overnight, this might work, other tasks that take multi value use it,

```
 - task: PublishTestResults@2 
    inputs:
      testResultsFormat: 'NUnit'
     testResultsFiles: | 
         $(System.DefaultWorkingDirectory)\Scripts\PesterTestResults.XML
         $(System.DefaultWorkingDirectory)\Scripts\AddNumbersResults.XML
      failTaskOnFailedTests: true
```
