### ISSUE TITLE
DevOps Pipeline Variables Not Working

### ISSUE THREAD

**Issue by flasherwrasse** [rfennell/AzurePipelines#643]
I have a variables set for [Name of file/page:] and they do not appear to work as intended. Does this option support variables? I had intended on creating a new file per release but if that is not supported I will just append to a concrete file.

Release-Notes/$(Date:yyyyMMdd)$(Hours)$(Minutes).md

Please let me know.

Thank you!

**Comment by rfennell** [comment]
Can't see why that won't work, I will do a test as soon as I get a chance

**Comment by flasherwrasse** [comment]
This was on WIKI Updater Tasks which I am using in conjunction with GenerateReleaseNotes (XPlat version).

https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-WIKIUpdater-Tasks&ssr=false#overview

**Comment by flasherwrasse** [comment]
##[error]Error: fatal: pathspec 'Release-Notes/$(Date:yyyyMMdd)$(Hours)$(Minutes).md' did not match any files

Options
[]  Replace the file in the WIKI
[]  Append to end of file in the WIKI
[x] Data is a file

**Comment by rfennell** [comment]
I have done some checking.

Inside the build pipeline (whether it use UI or YAML based) you can only access the [built in variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables). If you check this list you can see the date ones are not there. It seem the$(date) etc. are only available for the build name i.e. set prior to the pipeline starting.

So, you are getting the errors the $(date) is not being expanded, and the unexpanded value is being used as a file name that is invalid.

I can confirm using the build variables are fine as this is the technique I use for testing both the release note and wikiupdater

A snippit of the YAML is 

```
steps:
- task: richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes.XplatGenerate-Release-Notes.XplatGenerateReleaseNotes@2
  displayName: 'Generate Release Notes based on Release Comparision API V2 '
  inputs:
    outputfile: '$(System.DefaultWorkingDirectory)\$(RELEASE.ENVIRONMENTNAME)SortedList.md'
    outputVariableName: OutputTextSorted
    templateLocation: InLine
    inlinetemplate: |
         < all the template>     
    sortWi: true

- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks.WikiUpdaterTask.WikiUpdaterTask@1
  displayName: 'Git based WIKI Updater c'
  inputs:
    repo: 'dev.azure.com/richardfennell/Git%20project/_git/Git-project.wiki'
    filename: 'xPlatReleaseNotes/$(RELEASE.ENVIRONMENTNAME)SortedList.md'
    dataIsFile: true
    sourceFile: '$(System.DefaultWorkingDirectory)\$(RELEASE.ENVIRONMENTNAME)SortedList.md'
    message: 'Update from Release - $(Release.ReleaseName) with Creds'
    gitname: builduser
    gitemail: 'build@demo'
    useAgentToken: false
    user: richardfennell
    password: '$(AzureDevOpsPAT)'
    localpath: '$(System.DefaultWorkingDirectory)\repo1'

```

So to get around your problem, the technique I would use here is to set your build number to be something like 

```
$(Build.DefinitionName)_$(Date:yyyyMMdd)$(Hours)$(Minutes)
```

 Though I prefer to use variables I control to get a date in the form `MyBuild_1.0.20125.1`
 - So I create a major and minor variable that I update as changes occur
-  the build variable increments on the date
- the rev is the build on the day

```
$(Build.DefinitionName)_$(Major).$(Minor).$(Year:yy)$(DayOfYear).$(rev:r)
```

Either way in the release notes and WIKI updater use the `$(Build.BuildNumber)`

```
 filename: 'ReleaseNotes/$(Build.BuildNumber).md'
```

I think that makes it easier to associate the build with the document.
