### ISSUE TITLE
Add file name and new line at the begging of the .order file in wiki somehow gets trimmed and ends up in the first lineline

### ISSUE THREAD

**Issue by ipavlovi** [rfennell/AzurePipelines#723]
# Scenario

1. Release Notes are generated using Generate Release Notes Task and saved to the temp folder on agent
2. Release Notes are upoaded to wiki 
3. Update .order file to make new release notes appear on the top of the list of child files

# Problem
First two tasks are executed without problems. Third task prepends TRIMMED content so it ends up in the same line

> repo and project names have been redacted

```
steps:
- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks.WikiUpdaterTask.WikiUpdaterTask@1
  displayName: 'Git based WIKI File Updater'
  inputs:
    repo: 'dev.azure.com/********/***********/_git/TechnicalDocs.wiki'
    filename: 'Environments\$(Release.EnvironmentName)\Releases\.order'
    replaceFile: false
    appendToFile: false
    contents: |
     $(Release.ReleaseName)
     
    message: 'Auto-generated release notes for $(Release.ReleaseName) attempt $(Release.AttemptNumber)'
    gitname: '$(Release.RequestedFor)'
    gitemail: '$(Release.RequestedForEmail)'
    useAgentToken: true
```

Content property of the third task is multiline string (note | in YAML) but somehow new line and space characters are trimmed before concatenated with current file content

Note first line only. Line breaks in other lines have been manually added after each unsuccessful attempt to add new line

![image](https://user-images.githubusercontent.com/3251341/82764896-adc21880-9e12-11ea-8dc4-aa960acf837b.png)

**Comment by rfennell** [comment]
I have a repo of the problem, I will look into it

**Comment by rfennell** [comment]
The issue is that when the multiline content entry is passed into the task the trailing newlines have been removed. The task never sees them so can't process them.

The solution is to enter the newline as **`n**. This gives the required result e.g.

```
- task: WikiUpdaterTask@1
  displayName: 'Line feed test'
  inputs:
    repo: 'dev.azure.com/richardfennell/Git%20project/_git/Git-project.wiki'
    filename: 'fakeorder.md'
    replaceFile: false
    appendToFile: false
    contents: |
     $(Build.BuildNumber)`n
    message: 'Extra line'
    gitname: 'Build.RequestedForId'
    gitemail: 'Build.RequestedForEmail'
    password: '$(pat)'
```

Does that address your problem?
