### ISSUE TITLE
VersionDotNetCoreAssemblies "Add a Version field if missing" parameter cannot be enabled via the GUI

### ISSUE THREAD

**Issue by deadlydog** [rfennell/AzurePipelines#726]
**Describe the bug**
I am using the MS hosted Azure DevOps. In the `Version .Net Core Assemblies` task, when using a yaml pipeline, the `Add a Version field if missing` checkbox is always disabled.

**To Reproduce**
1. Create a new yaml build pipeline.
2. Add the `VersionDotNetCoreAssemblies` task by using the Visual Assist editor.
3. Try to enable the `Add a Version field if missing` field; you can't.

The resulting yaml would look something like this:

```yaml
    - task: VersionDotNetCoreAssemblies@2
      inputs:
        Path: '$(Build.SourcesDirectory)'
        VersionNumber: '$(versionNumber)'
        Injectversion: true
        FilenamePattern: '.csproj'
        OutputVersion: 'OutputedVersion'
```

**Expected behavior**
You should be able to check the box to enable the `Add a Version field if missing` behaviour.

**Screenshots**
You can see the checkbox is disabled in this screenshot.
![image](https://user-images.githubusercontent.com/1187140/83044576-98f7a780-a001-11ea-8980-81286a63e31f.png)

I tried adding text to the `The version field to update` textbox as well thinking that the 2 controls might be linked, but it did not work.

**Logs**
N/A

**What is the issue see:**
 - Azure DevOps Services (VSTS)

**Additional context**

The work around is to not use the Visual Assist GUI editor and update the yaml text directly by adding the `AddDefault: true` input parameter.

e.g.
```yaml
    - task: VersionDotNetCoreAssemblies@2
      inputs:
        Path: '$(Build.SourcesDirectory)'
        VersionNumber: '$(versionNumber)'
        Injectversion: true
        FilenamePattern: '.csproj'
        AddDefault: true
        OutputVersion: 'OutputedVersion'
```

Once you enable it via the yaml text, then the GUI checkbox is enabled and allows you to turn it on and off via the GUI.
