### ISSUE TITLE
Publish to Azure DevOps Wiki fails with Error: spawn git ENOENT

### ISSUE THREAD

**Issue by ipavlovi** [rfennell/AzurePipelines#738]
Release notes are successful generated but in the next step publish to Azure DevOps Wiki fails with following error:

```
Error: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Error: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

[tasklog_18.log](https://github.com/rfennell/AzurePipelines/files/4769684/tasklog_18.log)

## YAML Definition

```
steps:
- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks.WikiFolderUpdaterTask.WikiFolderUpdaterTask@1
  displayName: 'Upload Release Notes to Technical Docs Wiki'
  inputs:
    repo: 'dev.azure.com/********/********/_git/TechnicalDocs.wiki'
    targetFolder: 'Environments\$(Release.EnvironmentName)\Releases\'
    sourceFolder: '$(Agent.TempDirectory)'
    Filter: '**/$(Release.ReleaseName)*.md'
    message: 'Auto-generated release notes for $(Release.ReleaseName) attempt $(Release.AttemptNumber)'
    gitname: '$(Release.RequestedFor)'
    gitemail: '$(Release.RequestedForEmail)'
    useAgentToken: false
    user: ******
    password: '$(PAT)'
    injectExtraHeader: false
```

*I am getting the same outcome no matter I am using username and PAT, OAUTH token, or if credentials are passed via Header.*

## Agent Info

I have successfully tested the same task group using both azure-hosted and self-hosted agents with out any problems using OAUTH token. All release notes were successful published to the same git repo.

Once tests were all good I have added the same taskgroup to stages for our production environments. 

Self-hosted agents on both test and production environments are configured to run under local admin account as windows service.

PAT issued for agents have full access to Azure DevOps.

## Other info
- Debug log is in the attachment.
- It looks like it is related to #613 and #497
