### ISSUE TITLE
##[error]Error: Cannot find module 'handlebars' 

### ISSUE THREAD

**Issue by Joannazhx** [rfennell/AzurePipelines#832]
**Describe the bug**
In Custom Handlebars Extension, I try to add a function to sort array by 2 fields like in example AzurePipelines/SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 3/each_with_sort_by_field.js 

        const handlebars = require("handlebars");
        module.exports = {get_system_type_sort_by_field(relatedWorkItems, typeName1, typeName2, key1, key2, opts) {
            if(opts.data) {
                data  = handlebars.createFrame(opts.data) 
            }

            var foundList = [];
            for(var arrayCount = 0; arrayCount < relatedWorkItems.length ; arrayCount++){
                if(relatedWorkItems[arrayCount].fields['System.WorkItemType'] === typeName1 || 
                relatedWorkItems[arrayCount].fields['System.WorkItemType'] === typeName2){
                    var system_type = relatedWorkItems[arrayCount];
                    if (!foundList.includes(system_type)) {
                        foundList.push(system_type);
                    }
                }
            }

            // sort by 2 field
            foundList = foundList.sort (function (a, b) {
                var a1 = a.fields[key1]
                var b1 = b.fields[key1]
                var a2 = a.fields[key2]
                var b2 = b.fields[key2]

                if(a1 == b1){
                    return (a2 < b2) ? -1 : (a2 > b2) ? 1 : 0;
                }else{
                    return (a1 < b1) ? -1 : 1;
                }
            });
    
        
            // the iterator
            var len = foundList.length;
            var buffer = '';
            var i = -1;
    
            while (++i < len) {
            var item = foundList[i];
            data.index = I;
            item.index = i + 1;
            item.total = len;
            item.isFirst = i === 0;
            item.isLast = i === (len - 1);
            buffer += opts.fn(item, {data: data});
            }
            return buffer;
            }
        };

The first line const handlebars = require("handlebars")
error message ##[error]Error: Cannot find module 'handlebars' 

In the template, I use the function 
        {{#get_system_type_sort_by_field this.relatedWorkItems "Bug" "Product Backlog Item" "System.Title" "System.Id"}}
        - {{this.id}}  - {{lookup this.fields 'System.WorkItemType'}} - {{lookup this.fields 'System.State'}} 
        {{/get_system_type_sort_by_field}}

**Comment by rfennell** [comment]
I will try to repo the problem and get back to you

**Comment by rfennell** [comment]
The issue is the folder the custom script gets dumped into. The .js file it generates needs to be in the same folder as the other .js files so it can find the already downloaded modules. I am working out the best defaults for this, there will be a new build 3.19.x

Oh and you have a typo, I assume 

`data.index = I;`

would be 

`data.index = i;'

**Comment by Joannazhx** [comment]
Thanks, Richard!
I tried it again, and work well!
Also, I used another way to sort without the handlebar module looks like :

    get_system_type_sort_by_field(relatedWorkItems, typeName, key, opts) {

        var contextSorted = relatedWorkItems.concat().sort(function (a, b) {
            return (a.fields[key] - b.fields[key])
        });

        var output ='';
        var foundList = [];
        for(var arrayCount = 0; arrayCount < contextSorted.length ; arrayCount++){
            if(contextSorted[arrayCount].fields['System.WorkItemType'] === typeName){
                var system_type = contextSorted[arrayCount];
                if (!foundList.includes(system_type)) {
                    foundList.push(system_type);
                    output += opts.fn(system_type);
                }
            }
        }
        return output;
    },

**Comment by rfennell** [comment]
I have another solution, and I think it is the one a favour if you don't want inline extension. 

All you need to do is `npm install` any modules into the same folder the `custom.js` is in e.g.

```
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(System.DefaultWorkingDirectory)'
    customCommand: 'install handlebars'

- task: XplatGenerateReleaseNotes@3
  inputs:
    outputfile: '$(Build.ArtifactStagingDirectory)/releasenotes.md'
    templateLocation: 'File'
    templatefile: '$(System.DefaultWorkingDirectory)/template.hbs'
    customHandlebarsExtensionFile: 'custom.js'
    customHandlebarsExtensionFolder: '$(System.DefaultWorkingDirectory)'
````

Using this model you can install any modules you need, so much more flexible.
