### ISSUE TITLE
Can you provide sample template to compare with  the previous release and update the wiki document

### ISSUE THREAD

**Issue by swkoganti** [rfennell/AzurePipelines#863]
I'm following the Git-flow template.hbs to generate release notes and want to compare the previous build details in the release notes wiki document. can you provide me any sample template with the details how to compare previous build or Please navigate with any related links that will help to update release notes .

**Comment by rfennell** [comment]
You have a number of options, they depend on whether the task is being used in a multi-stage YAML or a legacy UI based release pipeline. The former has more options and its 'the future'.

| Option | Multi Stage YAML | UI Based Release |
|-|-|-|
| Place the task in a stage that is only run when you wish to generate release notes. Usually this will be guarded by branch based filters or manual approvals.  |  Requires `checkstages=true` parameter | Supported and you can override the stage name used for comparison using the `overrideStageName` parameter
| Set the task to look back for the last successful build that has a given tag |  Requires `checkstages=true` and the `tags` parameters| Not supported 
| Override the build that the task uses for comparison with a fixed value |  Requires `checkstages=true` and the `overrideBuildReleaseId` parameters | Requires the `overrideBuildReleaseId` parameter

In my pipelines (we are moving everything to multi-stage YAML over time) I used the task twice
- Run once for every build with `checkstages=false` as part of the build stage. So I get the build notes of what is in that build
- Run as part of the stage with `checkstages=true`  that is only run when I merge to a given branch that is the release branch. This is the release notes issued with a release.

You can see the documentation for all the features in the [WIKI ](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task) and the YAML usage [here](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task-YAML)

**Comment by swkoganti** [comment]
Thanks for your reply, I really appreciate it. In  **gitflow-template.hbs** template file I can see a parameter/variable **_template_** from "**{{#if (eq (template) 'production')}**" . From where are we getting the template value, is there a way to pass explicitly.

If I am directly using your template  **gitflow-template.hbs** , I am getting the blank release notes as it is not satisfying anyone of the if condition

**Comment by rfennell** [comment]
The sample GitFlow template was provided by @svengeance, it was provided as three files:

- [A readme describing the usage](https://github.com/rfennell/AzurePipelines/blob/main/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203/gitflow-readme.md)
- [The sample template]([url](https://github.com/rfennell/AzurePipelines/blob/main/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203/gitflow-template.hbs))
- [A custom extension](https://github.com/rfennell/AzurePipelines/blob/main/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203/gitflow-extension.js) that provides the `template` function.

You might need to alter the sample custom function and or the template to match your exact needs, as with all the samples

**Comment by svengeance** [comment]
Hello! Sorry @rfennell, hopefully having this example doesn't make your life too hard. If you have any ideas on clarification or simplification, or would like me to revisit the documentation for improval, let me know and I'll try to help.

@swkoganti As noted [here](https://github.com/rfennell/AzurePipelines/blob/main/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203/gitflow-readme.md#custom-helpers), you'll need to include this handlebars helper file to dynamically render the template **per-environment**, whether you're in dev/test/prod.

If you only wish to use one environment/template, the simplest way forward is to remove the if-block surrounding the template you want to use.

**Comment by swkoganti** [comment]
I can see a variable called $(ReleaseStage) custom helper extension template, is this a predefined variable getting the data from Azure devops pipeline? 
I am using the same variable in multistage yaml pipeline but it is not returning the stage name, can you help me here.

**Comment by rfennell** [comment]
The reason you don't see a ReleaseStage name in multi-stage YAML is because multi-stage YAML has no concept of releases.

To see the stage in the multi-stage YAML builds you need to set the parameter `CheckStage=true` and then the task considers the build variable `$(System.StageName)`

**Comment by rfennell** [comment]
The buildDetails.id is the one you need. This is an integer, you can also see it in the url in the browser when viewing a pipeline.

I usually find it by looking in the build lig or as I said the url

The build number is the number you assigned  e.g 1.2.3.4, so not what you need

**Comment by swkoganti** [comment]
Current build id is displayed in wiki with **Build Number**: {{buildDetails.id}},
I would like to display  overidebuildreleaseid in the wiki . Please suggest parameter/variable to display overidebuildreleaseid in wiki

![image](https://user-images.githubusercontent.com/73246093/99478579-a2176080-2922-11eb-9f73-c7ca23a5dc37.png)

**Comment by rfennell** [comment]
The build used for the compare will be loaded into the object `compareBuildDetails` so you can reference any of its properties in a template e.g. `{{compareBuildDetails.id}}'

**Comment by rfennell** [comment]
Without seeing the who YAML block for the release notes task I can't work out what you are dong, but normally I would expect it to be something similar to 

```
        - task: XplatGenerateReleaseNotes@3
          displayName: 'Generate release notes markdown file'
          inputs:
            outputfile: '$(Build.ArtifactStagingDirectory)\Changes_$(GitVersion.FullSemVer).md'
            templateLocation: 'File'
            templatefile: '$(Build.SourcesDirectory)\BuildReleaseNotes.md'
            dumpPayloadToConsole: false
            dumpPayloadToFile: false
            replaceFile: true
            getParentsAndChildren: false
            getAllParents: False
```

**Comment by Panda-Sharp** [comment]
@rfennell  thanks for your reply, here it is:

```
- task: XplatGenerateReleaseNotes@3
  condition: eq('${{ parameters.workItemId }}', '')
  displayName: 'Generate Internal Realease Notes'
  inputs:
    outputfile: '${{ parameters.releaseNotesFolder }}/$(Build.BuildNumber).md,${{ parameters.releaseNotesFolder }}/app-center.md,${{ parameters.releaseNotesFolder }}/gitflow-template.md'
    templateLocation: 'File'
    templatefile: '${{ parameters.workingDirectory }}/handlebars/templates/$(template),${{ parameters.workingDirectory }}/handlebars/templates/release-notes-app-center-template.hbs,${{ parameters.workingDirectory }}/handlebars/templates/gitflow-template.hbs'
    customHandlebarsExtensionFile: 'handlebars/extensions/each_with_group_by.js'
    customHandlebarsExtensionFolder: '${{ parameters.workingDirectory }}'  
    checkStage: true
    sortWi: true
    dumpPayloadToConsole: true
    dumpPayloadToFile: false
    replaceFile: true
    getParentsAndChildren: false
    getAllParents: false
    getIndirectPullRequests: false
    stopOnError: true
    considerPartiallySuccessfulReleases: true
    checkForManuallyLinkedWI: false
    wiqlFromTarget: 'WorkItems'
    getPRDetails: false
    getTestedBy: false
    ```
