### ISSUE TITLE
Enable prepend when updating release notes file

### ISSUE THREAD

**Issue by crega** [rfennell/AzurePipelines#888]
**Is your feature request related to a problem? Please describe.**
We use WIKI Updater Tasks tool, alot, and it would be nice if I could specity, prepending release.md file so the updated release.md always have newest content at top. 

**Describe the solution you'd like**
Option to define prepending when updating file , instead only appending.

**Describe alternatives you've considered**
Is to manually read generated and appended file, and then using powershell or something like that to manully
reoder content of .md file. I think that is wrong path to take :( It is far easier to prepend during updating, then reordering whole file content.
**Additional context**
None, i think it is clear what I mean :)

**Comment by rfennell** [comment]
I think the feature you require is already in the task

to append use these settings
```
- task: WikiFolderUpdaterTask@1
  inputs: 
    .. other settings
     replaceFile: False
     appendToFile: True
```

to prepend use these settings
```
- task: WikiFolderUpdaterTask@1
  inputs: 
    .. other settings
     replaceFile: False
     appendToFile: False
```
