### ISSUE TITLE
Replace spaces in Wiki filename

### ISSUE THREAD

**Issue by ElStupid** [rfennell/AzurePipelines#969]
I'm having the Wiki file updater adding a new file with every release. This works as it should.
However, I want to use the Releasename in the filename, but because of the spaces, it's not a valid name.

Please add a method to replace spaces with dashes (which is standard behaviour when you add a new file through the editor with a space in the title).

Thanks!

![image](https://user-images.githubusercontent.com/5188875/110624831-02b2fd80-819f-11eb-8397-703b621eaf4f.png)

![image](https://user-images.githubusercontent.com/5188875/110625041-3a21aa00-819f-11eb-92ce-d89d369aa1d3.png)

![image](https://user-images.githubusercontent.com/5188875/110624443-828c9800-819e-11eb-8496-e5f9ceda176e.png)

**Comment by rfennell** [comment]
Seems a sensible suggestion, it is on the backlog. Not sure when it will get done

**Comment by ElStupid** [comment]
Allright that's good enough for me, thanks ;)

**Comment by rfennell** [comment]
This chnage is being publish as 1.23.3.

To enable the feature you have to set a new parameter (done this way so I don't alter default behaviour)

```
            - task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks-DEV.WikiUpdaterTask.WikiUpdaterTask@1
              displayName: 'Git based WIKI Updater - GitHub folder with spaces'
              inputs:
                ... other parameters
                filename: TestFolder/Page From Wiki Updater and Spaces.md
                fixSpaces: true
```
